// ── Glosario Tributario Colombiano ──

export interface GlosarioTerm {
  termino: string;
  definicion: string;
  articulos?: string[]; // ET article references
  relacionados?: string[]; // related terms
}

export const GLOSARIO: GlosarioTerm[] = [
  // ─── A ───
  { termino: "Abuso tributario", definicion: "Operacion o serie de operaciones cuyo proposito principal es obtener un beneficio fiscal sin razon economica o comercial aparente. La DIAN puede recaracterizar estas operaciones.", articulos: ["869"], relacionados: ["Evasion", "Elusion"] },
  { termino: "Activo fijo", definicion: "Bien de propiedad del contribuyente que no se enajena dentro del giro ordinario de sus negocios. Su venta puede generar ganancia ocasional si fue poseido por mas de 2 anos.", articulos: ["60", "300"], relacionados: ["Ganancia ocasional", "Costo fiscal"] },
  { termino: "Agente retenedor", definicion: "Persona natural o juridica obligada a practicar la retencion en la fuente sobre pagos o abonos en cuenta.", articulos: ["368"], relacionados: ["Retencion en la fuente", "Autorretencion"] },
  { termino: "Agente autorretenedor", definicion: "Contribuyente autorizado por la DIAN para practicarse a si mismo la retencion en la fuente sobre sus ingresos, en vez de que lo haga el pagador.", articulos: ["366-1"], relacionados: ["Autorretencion", "Agente retenedor"] },
  { termino: "Amortizacion fiscal", definicion: "Distribucion del costo de activos intangibles o cargos diferidos durante su vida util estimada. Reduce la renta liquida del contribuyente.", articulos: ["142", "143"], relacionados: ["Depreciacion fiscal", "Deduccion"] },
  { termino: "Anticipo de renta", definicion: "Pago anticipado del impuesto de renta del periodo siguiente, calculado como porcentaje del impuesto del periodo actual. Primera vez 25%, segunda 50%, tercera en adelante 75%.", articulos: ["807", "808", "809"], relacionados: ["Declaracion de renta", "Retencion en la fuente"] },
  { termino: "Aportes a pension", definicion: "Contribucion obligatoria del 16% sobre el IBC (4% trabajador + 12% empleador) destinada al fondo de pensiones. El aporte del trabajador es INCRNGO.", articulos: ["55", "126-1"], relacionados: ["Seguridad social", "INCRNGO", "IBC"] },
  { termino: "Aportes a salud", definicion: "Contribucion obligatoria del 12.5% sobre el IBC (4% trabajador + 8.5% empleador) destinada al sistema de salud. No es deducible en renta para personas naturales.", articulos: ["56"], relacionados: ["Seguridad social", "IBC"] },
  { termino: "Aportes voluntarios a pension", definicion: "Aportes adicionales al fondo de pensiones obligatorias o a fondos de pensiones voluntarias. Son renta exenta hasta el 30% del ingreso (dentro del limite del 40%).", articulos: ["126-1"], relacionados: ["Renta exenta", "Limite del 40%", "Cuentas AFC"] },
  { termino: "ARL", definicion: "Administradora de Riesgos Laborales. Entidad que cubre los riesgos de accidentes de trabajo y enfermedad profesional. La cotizacion la paga en su totalidad el empleador.", relacionados: ["Seguridad social", "IBC", "Parafiscales"] },
  { termino: "Autorretencion", definicion: "Mecanismo por el cual el mismo beneficiario del pago se practica la retencion en la fuente. Requiere autorizacion previa de la DIAN.", articulos: ["366-1"], relacionados: ["Retencion en la fuente", "Agente autorretenedor"] },
  { termino: "Avaluo catastral", definicion: "Valor asignado a un predio por la autoridad catastral. Se usa como referencia para el impuesto predial y como valor patrimonial minimo del inmueble en renta.", articulos: ["277"], relacionados: ["Valor patrimonial", "Impuesto predial"] },

  // ─── B ───
  { termino: "Base gravable", definicion: "Valor monetario o unidad de medida sobre el cual se aplica la tarifa del impuesto para establecer el valor del tributo.", articulos: ["338"], relacionados: ["Renta liquida gravable", "Hecho generador"] },
  { termino: "Base gravable especial del IVA", definicion: "Base diferente al valor total de la operacion, aplicable a ciertos bienes y servicios (juegos de suerte, financieros, derivados). Se calcula segun reglas especificas del ET.", articulos: ["447", "448", "449"], relacionados: ["IVA", "Bien gravado"] },
  { termino: "Base minima de retencion", definicion: "Monto a partir del cual se practica retencion en la fuente. Varia segun el concepto: salarios (95 UVT), servicios (4 UVT), compras (27 UVT), arrendamientos (27 UVT).", articulos: ["383", "392"], relacionados: ["Retencion en la fuente", "UVT"] },
  { termino: "Beneficiario final", definicion: "Persona natural que directa o indirectamente posee o controla al menos el 5% de una persona juridica, o se beneficia de sus operaciones. Debe registrarse en el RUB de la DIAN.", articulos: ["631-5", "631-6"], relacionados: ["RUT", "SAGRILAFT"] },
  { termino: "Beneficio de auditoria", definicion: "Reduccion del periodo de firmeza de la declaracion de renta cuando el contribuyente incrementa su impuesto en cierto porcentaje respecto al ano anterior.", articulos: ["689-3"], relacionados: ["Firmeza de la declaracion", "Declaracion de renta"] },
  { termino: "Bien excluido de IVA", definicion: "Bien que por ley no causa IVA. No genera derecho a IVA descontable para el productor o comercializador.", articulos: ["424", "425", "426"], relacionados: ["Bien exento de IVA", "IVA"] },
  { termino: "Bien exento de IVA", definicion: "Bien gravado a tarifa 0%. El responsable puede solicitar devolucion del IVA pagado en sus compras (IVA descontable).", articulos: ["477", "478", "479"], relacionados: ["Bien excluido de IVA", "IVA descontable"] },
  { termino: "Bien gravado", definicion: "Bien cuya venta genera IVA a la tarifa general del 19% o a una tarifa diferencial (5%). El vendedor debe facturar y recaudar el IVA.", articulos: ["420", "468"], relacionados: ["IVA", "Tarifa general de IVA"] },

  // ─── C ───
  { termino: "Causalidad", definicion: "Principio que exige que un gasto tenga relacion directa con la actividad generadora de renta para ser deducible. Junto con necesidad y proporcionalidad, forma los requisitos de las deducciones.", articulos: ["107"], relacionados: ["Deduccion", "Necesidad", "Proporcionalidad"] },
  { termino: "Cedula de dividendos", definicion: "Categoria del impuesto de renta para personas naturales que grava los dividendos y participaciones. Se subdivide en sub-cedula 1 (no gravados, Art. 49) y sub-cedula 2 (gravados).", articulos: ["342", "343"], relacionados: ["Dividendos gravados", "Dividendos no gravados", "Cedula general"] },
  { termino: "Cedula de pensiones", definicion: "Categoria del impuesto de renta que grava las pensiones de jubilacion, vejez, invalidez y sobrevivientes. Son exentas las primeras 12.000 UVT anuales.", articulos: ["337", "206"], relacionados: ["Renta exenta", "Cedula general"] },
  { termino: "Cedula general", definicion: "Categoria del impuesto de renta para personas naturales residentes que agrupa rentas de trabajo, capital y no laborales. Se depura conjuntamente y se aplica la tabla del Art. 241.", articulos: ["335", "336", "241"], relacionados: ["Renta liquida gravable", "Tabla Art. 241", "Cedula de dividendos"] },
  { termino: "Certificado de retencion", definicion: "Documento que el agente retenedor debe expedir al retenido, certificando los valores pagados y las retenciones practicadas durante el ano. Plazo: 15 de marzo.", articulos: ["378", "379", "381"], relacionados: ["Retencion en la fuente", "Agente retenedor"] },
  { termino: "CHC (Compania Holding Colombiana)", definicion: "Regimen especial para sociedades nacionales cuyo objeto principal sea la tenencia de valores de participacion en sociedades del exterior. Dividendos e ingresos por enajenacion de participaciones no gravados.", articulos: ["894", "895", "896", "897", "898"], relacionados: ["Establecimiento permanente", "Regimen tributario especial"] },
  { termino: "Compensacion de perdidas fiscales", definicion: "Derecho del contribuyente a restar perdidas de anos anteriores contra la renta liquida del periodo actual. Las perdidas se pueden compensar en los 12 anos siguientes.", articulos: ["147"], relacionados: ["Renta liquida gravable", "Renta presuntiva"] },
  { termino: "Compensacion tributaria", definicion: "Mecanismo para aplicar saldos a favor de un impuesto contra deudas del mismo u otros impuestos nacionales. Requiere solicitud ante la DIAN.", articulos: ["815", "816"], relacionados: ["Devolucion de saldos a favor", "Saldo a favor"] },
  { termino: "Comparacion patrimonial", definicion: "Mecanismo de control por el cual la DIAN puede determinar como renta gravable los incrementos patrimoniales no justificados.", articulos: ["236", "237"], relacionados: ["Patrimonio liquido", "Renta liquida gravable"] },
  { termino: "Conciliacion fiscal", definicion: "Formato (Formato 2516) que concilia las diferencias entre la contabilidad NIIF y las normas fiscales. Obligatorio para contribuyentes del Grupo 1 y 2 NIIF.", articulos: ["772-1"], relacionados: ["Diferencias temporarias", "Valor patrimonial"] },
  { termino: "Contribuyente", definicion: "Persona natural o juridica respecto de quien se realiza el hecho generador de la obligacion tributaria.", articulos: ["2"], relacionados: ["Sujeto pasivo", "Declarante"] },
  { termino: "Convenio de doble imposicion (CDI)", definicion: "Tratado internacional para evitar la doble tributacion entre dos paises. Colombia tiene CDI vigentes con Espana, Chile, Mexico, Canada, Suiza, entre otros. Permite credito tributario o exencion.", relacionados: ["Credito tributario", "Principio de territorialidad"] },
  { termino: "Correccion de la declaracion", definicion: "Modificacion de una declaracion tributaria ya presentada. Si aumenta el impuesto, genera sancion del 10% (Art. 644). Si lo disminuye, requiere proceso del Art. 589.", articulos: ["588", "589", "644"], relacionados: ["Sancion por correccion", "Firmeza de la declaracion"] },
  { termino: "Costo fiscal", definicion: "Valor de adquisicion de un activo, ajustado segun las normas tributarias (reajustes fiscales, depreciacion, mejoras). Determina la utilidad o perdida en la enajenacion.", articulos: ["58", "59", "60", "69"], relacionados: ["Activo fijo", "Ganancia ocasional", "Valor patrimonial"] },
  { termino: "Cotizante", definicion: "Persona que realiza aportes al sistema de seguridad social (salud, pension, ARL). Puede ser dependiente (vinculado laboralmente) o independiente.", relacionados: ["Seguridad social", "IBC", "PILA"] },
  { termino: "Credito tributario", definicion: "Derecho a descontar del impuesto colombiano los impuestos pagados en el exterior sobre la misma renta. Aplica cuando hay CDI o por norma unilateral del Art. 254 ET.", articulos: ["254"], relacionados: ["Convenio de doble imposicion", "Descuento tributario"] },
  { termino: "Criptoactivos (tributacion)", definicion: "Los criptoactivos se tratan como activos intangibles. Las ganancias por su enajenacion tributan como renta ordinaria (si se negocian habitualmente) o como ganancia ocasional (si se mantuvieron mas de 2 anos).", relacionados: ["Ganancia ocasional", "Renta ordinaria", "Activo fijo"] },
  { termino: "Cuentas AFC", definicion: "Cuentas de Ahorro para el Fomento de la Construccion (AFC) o Ahorro Voluntario Contractual (AVC). Los aportes son renta exenta hasta el 30% del ingreso, destinados a compra de vivienda.", articulos: ["126-4"], relacionados: ["Renta exenta", "Aportes voluntarios a pension", "Limite del 40%"] },
  { termino: "Cuatro por mil (4x1000)", definicion: "Nombre coloquial del GMF. Se cobra 4 pesos por cada 1.000 pesos en movimientos financieros (retiros, traslados, pagos). Exencion: una cuenta marcada con movimientos hasta 350 UVT mensuales.", articulos: ["871", "879"], relacionados: ["GMF", "Exclusion del GMF"] },

  // ─── D ───
  { termino: "Declaracion tributaria", definicion: "Documento formal en el que el contribuyente informa a la DIAN sus ingresos, patrimonio, costos, deducciones e impuestos. Incluye renta, IVA, retenciones, ICA, entre otros.", articulos: ["574", "596"], relacionados: ["Declarante", "Formulario 210", "Formulario 110"] },
  { termino: "Declarante", definicion: "Persona obligada a presentar declaracion tributaria ante la DIAN. Los topes para personas naturales son: patrimonio > 4.500 UVT o ingresos > 1.400 UVT, entre otros.", articulos: ["591", "592"], relacionados: ["Contribuyente", "No declarante"] },
  { termino: "Deduccion", definicion: "Gastos realizados durante el ano gravable que tienen relacion de causalidad, necesidad y proporcionalidad con la actividad productora de renta.", articulos: ["104", "105", "107"], relacionados: ["Renta exenta", "Costos", "Causalidad"] },
  { termino: "Dependientes economicos", definicion: "Personas a cargo del trabajador que generan una deduccion en renta hasta 72 UVT mensuales: hijos menores de 18 (o hasta 23 si estudian), conyugue o padres sin ingresos.", articulos: ["387"], relacionados: ["Deduccion", "Cedula general", "Depuracion"] },
  { termino: "Depreciacion fiscal", definicion: "Desgaste o deterioro de activos fijos tangibles distribuido durante su vida util fiscal. Se acepta como deduccion en el impuesto de renta. Metodos: linea recta o reduccion de saldos.", articulos: ["128", "131", "134", "137"], relacionados: ["Amortizacion fiscal", "Activo fijo", "Deduccion"] },
  { termino: "Depuracion", definicion: "Proceso de restar de los ingresos los conceptos permitidos (INCRNGO, costos, deducciones, rentas exentas) para obtener la base gravable.", articulos: ["388"], relacionados: ["Base gravable", "INCRNGO", "Deduccion"] },
  { termino: "Descuento tributario", definicion: "Valor que se resta directamente del impuesto a pagar (no de la base gravable). Incluye IVA en activos fijos productivos, donaciones, impuestos pagados en el exterior.", articulos: ["254", "255", "256", "257-1"], relacionados: ["Credito tributario", "Impuesto neto de renta"] },
  { termino: "Devolucion de saldos a favor", definicion: "Proceso para obtener el reintegro de valores pagados en exceso al fisco. Plazo de la DIAN para resolver: 50 dias habiles (30 si es devolucion automatica). Se presenta por MUISCA.", articulos: ["850", "854", "855", "857"], relacionados: ["Saldo a favor", "Compensacion tributaria"] },
  { termino: "Diferencias temporarias", definicion: "Diferencias entre la base contable (NIIF) y la base fiscal de activos y pasivos que se reversan en periodos futuros. Generan impuesto diferido en contabilidad.", articulos: ["772-1"], relacionados: ["Conciliacion fiscal", "Valor patrimonial"] },
  { termino: "Dividendos gravados", definicion: "Dividendos distribuidos con cargo a utilidades que no pagaron impuesto corporativo (no cumplen Art. 49 ET). Se gravan como renta ordinaria con la tarifa del Art. 242.", articulos: ["49", "242", "245"], relacionados: ["Dividendos no gravados", "Cedula de dividendos"] },
  { termino: "Dividendos no gravados", definicion: "Dividendos distribuidos con cargo a utilidades que ya pagaron impuesto corporativo (cumplen Art. 49 ET). Personas naturales residentes pagan tarifa progresiva a partir de 1.090 UVT.", articulos: ["49", "242"], relacionados: ["Dividendos gravados", "Cedula de dividendos"] },
  { termino: "Doble tributacion", definicion: "Situacion en la que un mismo ingreso es gravado por dos jurisdicciones fiscales diferentes. Se mitiga mediante CDI, creditos tributarios o exenciones.", relacionados: ["Convenio de doble imposicion", "Credito tributario", "Principio de territorialidad"] },
  { termino: "Documento equivalente", definicion: "Documento que sustituye a la factura de venta en operaciones con no obligados a facturar, como el tiquete de caja, boleta de cine, extracto bancario, entre otros.", articulos: ["616-1"], relacionados: ["Factura electronica", "Documento soporte"] },
  { termino: "Documento soporte", definicion: "Documento que emite el adquirente de bienes/servicios cuando su proveedor no esta obligado a facturar. Se transmite electronicamente a la DIAN para soportar costos y deducciones.", articulos: ["616-1"], relacionados: ["Factura electronica", "Documento equivalente"] },

  // ─── E ───
  { termino: "Economia naranja (beneficios)", definicion: "Incentivo tributario para empresas de industrias creativas con ingresos < 80.000 UVT. Rentas exentas por 5 anos si cumplen requisitos de empleo minimo y aprobacion MinCultura/MinTIC.", articulos: ["235-2"], relacionados: ["Renta exenta", "Zona franca"] },
  { termino: "Elusion", definicion: "Uso de mecanismos legales para reducir la carga tributaria de forma artificiosa, sin violar la ley pero desvirtuando su espiritu. La DIAN puede aplicar la norma anti-abuso.", articulos: ["869"], relacionados: ["Abuso tributario", "Evasion"] },
  { termino: "Emplazamiento para corregir", definicion: "Acto administrativo de la DIAN que invita al contribuyente a corregir su declaracion cuando detecta inconsistencias. Si se corrige despues del emplazamiento, la sancion sube al 20%.", articulos: ["685", "644"], relacionados: ["Correccion de la declaracion", "Sancion por correccion"] },
  { termino: "Emplazamiento para declarar", definicion: "Acto administrativo de la DIAN que requiere al contribuyente que no ha presentado la declaracion tributaria estando obligado. Si no declara, la DIAN puede imponer sancion y liquidacion de aforo.", articulos: ["715"], relacionados: ["Declarante", "Sancion por extemporaneidad"] },
  { termino: "ESAL (Entidad Sin Animo de Lucro)", definicion: "Entidad cuyo excedente se reinvierte en su objeto social (fundaciones, asociaciones, cooperativas). Puede pertenecer al Regimen Tributario Especial con tarifa del 20% sobre el beneficio neto.", articulos: ["356", "357", "358", "359"], relacionados: ["Regimen tributario especial", "Donaciones"] },
  { termino: "Establecimiento permanente", definicion: "Lugar fijo de negocios a traves del cual una empresa extranjera realiza toda o parte de su actividad en Colombia. Tributa como persona juridica nacional sobre renta de fuente colombiana.", articulos: ["20-1", "20-2"], relacionados: ["Renta de fuente nacional", "CHC"] },
  { termino: "Estampillas", definicion: "Tributos territoriales que gravan ciertos actos o documentos, como contratos publicos. Son administrados por departamentos y municipios con destino a inversion social.", relacionados: ["Impuestos territoriales", "ICA"] },
  { termino: "Evasion", definicion: "Conducta ilegal de ocultar ingresos, inflar costos o no declarar para pagar menos impuestos. La evasion tributaria es un delito penal en Colombia (Ley 2277 de 2022).", articulos: ["434-A"], relacionados: ["Abuso tributario", "Elusion"] },
  { termino: "Exclusion del GMF", definicion: "Derecho a marcar una cuenta bancaria para exencion del 4x1000 en movimientos hasta 350 UVT mensuales ($18.330.900). Solo se puede marcar una cuenta por persona.", articulos: ["879"], relacionados: ["GMF", "Cuatro por mil"] },
  { termino: "Exoneracion Art. 114-1", definicion: "Empleadores de personas juridicas exonerados de aportes a salud (8.5%), SENA (2%) e ICBF (3%) por trabajadores que devenguen menos de 10 SMLMV.", articulos: ["114-1"], relacionados: ["Parafiscales", "Seguridad social"] },
  { termino: "Exportacion exenta de IVA", definicion: "Los bienes exportados tienen tarifa de IVA del 0%. El exportador puede solicitar devolucion del IVA pagado en sus compras (IVA descontable).", articulos: ["479", "481"], relacionados: ["Bien exento de IVA", "IVA descontable"] },

  // ─── F ───
  { termino: "Facilidad de pago", definicion: "Acuerdo con la DIAN para pagar deudas tributarias en cuotas. Requiere garantia (poliza, hipoteca) si el plazo supera 1 ano. Los intereses de mora siguen corriendo.", articulos: ["814", "814-1"], relacionados: ["Intereses de mora tributarios", "Titulo ejecutivo"] },
  { termino: "Factura electronica", definicion: "Documento digital que soporta la venta de bienes y prestacion de servicios, validado previamente por la DIAN. Es obligatoria para todos los responsables de IVA y sujetos no exentos.", articulos: ["616-1", "617"], relacionados: ["Documento soporte", "Documento equivalente", "Habilitacion DIAN"] },
  { termino: "Firmeza de la declaracion", definicion: "Fecha a partir de la cual la declaracion tributaria queda en firme y no puede ser modificada por la DIAN. Regla general: 3 anos desde el vencimiento del plazo para declarar.", articulos: ["714"], relacionados: ["Beneficio de auditoria", "Correccion de la declaracion"] },
  { termino: "Fondo de solidaridad pensional", definicion: "Aporte adicional del 1% al 2% sobre el IBC para trabajadores con ingresos superiores a 4 SMLMV. Financia pensiones de personas de bajos recursos.", articulos: ["204"], relacionados: ["Aportes a pension", "Seguridad social"] },
  { termino: "Formulario 110", definicion: "Formulario de declaracion de renta y complementarios para personas juridicas y asimiladas. Se presenta anualmente por MUISCA.", relacionados: ["Declaracion tributaria", "Persona juridica", "Formulario 210"] },
  { termino: "Formulario 210", definicion: "Formulario de declaracion de renta y complementarios para personas naturales y sucesiones iliquidas. Se presenta anualmente por MUISCA.", relacionados: ["Declaracion tributaria", "Persona natural", "Formulario 110"] },

  // ─── G ───
  { termino: "Ganancia ocasional", definicion: "Ingreso proveniente de actividades no habituales del contribuyente, como venta de activos fijos poseidos mas de 2 anos, herencias, loterias o donaciones. Tarifa general: 15%.", articulos: ["299", "300", "301", "302", "303", "304", "313", "314"], relacionados: ["Renta ordinaria", "Activo fijo"] },
  { termino: "GMF", definicion: "Gravamen a los Movimientos Financieros (4 por mil). Impuesto que grava las transacciones financieras realizadas por los usuarios del sistema financiero.", articulos: ["871", "872"], relacionados: ["Cuatro por mil", "Exclusion del GMF"] },
  { termino: "Gradualidad de sanciones (Art. 640)", definicion: "Principio que permite reducir sanciones tributarias: 75% si se corrige antes del emplazamiento, 50% despues del emplazamiento y antes de la resolucion sancion.", articulos: ["640"], relacionados: ["Sancion por extemporaneidad", "Sancion por correccion", "Sancion minima"] },

  // ─── H ───
  { termino: "Habilitacion DIAN", definicion: "Proceso tecnico por el cual la DIAN autoriza a un contribuyente o proveedor tecnologico para emitir facturas electronicas. Incluye pruebas de validacion en el sistema de la DIAN.", relacionados: ["Factura electronica", "RADIAN"] },
  { termino: "Hecho generador", definicion: "Presupuesto establecido por la ley para tipificar el tributo y cuya realizacion origina el nacimiento de la obligacion tributaria.", relacionados: ["Base gravable", "Sujeto pasivo"] },

  // ─── I ───
  { termino: "IBC", definicion: "Ingreso Base de Cotizacion. Base sobre la cual se calculan los aportes a seguridad social (salud, pension, ARL). Para empleados es el salario; para independientes es el 40% de los ingresos.", relacionados: ["Seguridad social", "SMLMV", "PILA"] },
  { termino: "ICA", definicion: "Impuesto de Industria y Comercio. Tributo municipal que grava la realizacion de actividades industriales, comerciales o de servicios. Tarifas varian por municipio (2 a 14 por mil).", relacionados: ["Impuestos territoriales", "ReteICA", "SIMPLE"] },
  { termino: "Impuesto a bebidas azucaradas", definicion: "Impuesto creado por Ley 2277 de 2022 que grava la produccion e importacion de bebidas con azucar anadida. Tarifa: $28/100ml (2023, ajustable con IPC).", relacionados: ["Impuesto saludable", "Impuesto al plastico"] },
  { termino: "Impuesto al patrimonio", definicion: "Impuesto que grava el patrimonio liquido de personas naturales superior a 72.000 UVT. Tarifas progresivas: 0.5%, 1% y 1.5%. Vigente entre 2023-2026.", articulos: ["292-3", "294-3", "295-3", "296-3"], relacionados: ["Patrimonio liquido", "Patrimonio bruto"] },
  { termino: "Impuesto al plastico de un solo uso", definicion: "Impuesto sobre la venta o importacion de envases y empaques plasticos de un solo uso. Tarifa: $50/gramo de envase. Creado por Ley 2277/2022.", relacionados: ["Impuesto saludable", "Impuesto a bebidas azucaradas"] },
  { termino: "Impuesto de registro", definicion: "Tributo departamental que grava la inscripcion de actos, contratos o negocios juridicos en camaras de comercio u oficinas de registro de instrumentos publicos.", relacionados: ["Impuestos territoriales", "Estampillas"] },
  { termino: "Impuesto de timbre", definicion: "Impuesto que grava documentos publicos o privados cuando alguna de las partes es una entidad publica. Tarifa: 0% actualmente para la mayoria de documentos, salvo salida del pais.", articulos: ["519", "530"], relacionados: ["Impuesto de registro"] },
  { termino: "Impuesto de vehiculos", definicion: "Tributo departamental anual sobre la propiedad de vehiculos automotores. Tarifas progresivas segun valor comercial del vehiculo: 1.5%, 2.5% o 3.5%.", relacionados: ["Impuestos territoriales", "Impuesto predial"] },
  { termino: "Impuesto Nacional al Consumo (INC)", definicion: "Impuesto que grava la prestacion de servicios de restaurantes (8%), telefonia celular (4%) y venta de bienes como vehiculos y aeronaves. No genera IVA descontable.", articulos: ["512-1", "512-2"], relacionados: ["IVA", "SIMPLE"] },
  { termino: "Impuesto predial", definicion: "Tributo municipal anual sobre bienes inmuebles. Se calcula sobre el avaluo catastral con tarifas fijadas por cada municipio (entre 1 y 16 por mil).", relacionados: ["Avaluo catastral", "Impuestos territoriales"] },
  { termino: "Impuesto saludable (ultraprocesados)", definicion: "Impuesto creado por Ley 2277 de 2022 que grava la venta e importacion de productos comestibles ultraprocesados y bebidas azucaradas con contenido excesivo de sodio, azucar o grasas.", relacionados: ["Impuesto a bebidas azucaradas", "Impuesto al plastico de un solo uso"] },
  { termino: "Impuestos territoriales", definicion: "Tributos administrados por departamentos y municipios: ICA, predial, vehiculos, estampillas, registro, entre otros. No los administra la DIAN sino las secretarias de hacienda locales.", relacionados: ["ICA", "Impuesto predial", "Impuesto de vehiculos"] },
  { termino: "INCRNGO", definicion: "Ingresos No Constitutivos de Renta ni Ganancia Ocasional. Ingresos que por disposicion legal se excluyen de la base gravable: aportes obligatorios a pension, utilidades Art. 49, dividendos no gravados.", articulos: ["36", "55", "56-2"], relacionados: ["Renta exenta", "Deduccion"] },
  { termino: "Intereses de mora tributarios", definicion: "Intereses que se causan por el pago extemporaneo de impuestos. Se liquidan diariamente a la tasa de usura vigente certificada por la Superintendencia Financiera.", articulos: ["634", "635"], relacionados: ["Facilidad de pago", "Sancion por extemporaneidad"] },
  { termino: "Intereses de vivienda (deduccion)", definicion: "Deduccion por intereses pagados en creditos de vivienda del trabajador. Limite: 100 UVT mensuales (1.200 UVT anuales). Aplica tanto para compra como para leasing habitacional.", articulos: ["119"], relacionados: ["Deduccion", "Cuentas AFC", "Limite del 40%"] },
  { termino: "IVA", definicion: "Impuesto al Valor Agregado. Impuesto indirecto que grava la venta de bienes, la prestacion de servicios y las importaciones. Tarifa general: 19%.", articulos: ["420", "468"], relacionados: ["Bien exento de IVA", "Bien excluido de IVA", "IVA descontable"] },
  { termino: "IVA descontable", definicion: "IVA pagado en la adquisicion de bienes y servicios que se relacionan con operaciones gravadas o exentas. Se resta del IVA generado para determinar el saldo a pagar o a favor.", articulos: ["485", "486", "488"], relacionados: ["IVA", "Prorrateo de IVA"] },
  { termino: "IVA generado", definicion: "IVA cobrado en la venta de bienes y prestacion de servicios gravados. Constituye la obligacion del responsable con el Estado. Se resta el IVA descontable.", articulos: ["437"], relacionados: ["IVA descontable", "Responsable de IVA"] },

  // ─── J ───
  { termino: "Jurisdiccion no cooperante", definicion: "Pais o territorio con tarifa nominal del impuesto sobre la renta inferior al 17.5%, o que no intercambia informacion tributaria con Colombia. Operaciones con estas jurisdicciones tienen reglas especiales.", articulos: ["260-7"], relacionados: ["Precios de transferencia", "Paraiso fiscal"] },

  // ─── L ───
  { termino: "Limite del 40%", definicion: "Tope maximo para la suma de rentas exentas y deducciones imputables a la cedula general de personas naturales: no pueden exceder el 40% del ingreso neto (equivalente a 5.040 UVT anuales).", articulos: ["336"], relacionados: ["Renta exenta del 25%", "Aportes voluntarios a pension", "Cedula general"] },
  { termino: "Liquidacion oficial", definicion: "Acto administrativo de la DIAN que modifica o determina oficialmente el impuesto a cargo del contribuyente. Puede ser de revision, correccion aritmetica o de aforo.", articulos: ["702", "697", "717"], relacionados: ["Requerimiento especial", "Recurso de reconsideracion"] },

  // ─── M ───
  { termino: "Medicina prepagada", definicion: "Deduccion por pagos de planes de medicina complementaria o prepagada para el trabajador, conyugue e hijos. Limite: 16 UVT mensuales (192 UVT anuales).", articulos: ["387"], relacionados: ["Deduccion", "Dependientes economicos", "Limite del 40%"] },
  { termino: "Mega-inversiones", definicion: "Incentivo para inversiones superiores a 30 millones de UVT que generen al menos 250 empleos directos. Tarifa de renta del 27% por 20 anos y depreciacion acelerada.", articulos: ["235-3", "235-4"], relacionados: ["Zona franca", "ZOMAC"] },
  { termino: "MUISCA", definicion: "Modelo Unico de Ingresos, Servicio y Control Automatizado. Plataforma tecnologica de la DIAN para la presentacion de declaraciones, facturacion electronica, RUT y demas tramites.", relacionados: ["DIAN", "RUT", "Factura electronica"] },

  // ─── N ───
  { termino: "NIT", definicion: "Numero de Identificacion Tributaria. Numero unico asignado por la DIAN a cada contribuyente (persona natural o juridica) para su identificacion en los tramites tributarios.", articulos: ["555"], relacionados: ["RUT", "DIAN"] },
  { termino: "No declarante", definicion: "Persona natural que no supera los topes legales para declarar renta: patrimonio <= 4.500 UVT, ingresos <= 1.400 UVT, consumos <= 1.400 UVT, consignaciones <= 1.400 UVT.", articulos: ["592", "593", "594"], relacionados: ["Declarante", "Contribuyente"] },
  { termino: "Nomina electronica", definicion: "Documento electronico que transmite al sistema de la DIAN la informacion de pagos y deducciones de la nomina de los empleados. Requisito para soportar costos y deducciones laborales.", articulos: ["616-1"], relacionados: ["Factura electronica", "Documento soporte"] },
  { termino: "Normalizacion tributaria", definicion: "Impuesto complementario para declarar activos omitidos o eliminar pasivos inexistentes. Incentiva la transparencia patrimonial ante la DIAN.", relacionados: ["Patrimonio bruto", "Patrimonio liquido"] },
  { termino: "Nota credito", definicion: "Documento que anula o modifica parcialmente una factura electronica. Se emite cuando hay devolucion de bienes, descuentos posteriores o anulacion de la factura.", relacionados: ["Factura electronica", "Nota debito"] },
  { termino: "Nota debito", definicion: "Documento que modifica una factura electronica para aumentar su valor. Se emite por intereses de mora, ajustes de precio u otros cargos adicionales.", relacionados: ["Factura electronica", "Nota credito"] },

  // ─── O ───
  { termino: "Obras por impuestos", definicion: "Mecanismo que permite pagar hasta el 50% del impuesto de renta mediante la ejecucion directa de obras en zonas ZOMAC. Aprobacion previa de la ART.", articulos: ["238", "800-1"], relacionados: ["ZOMAC", "Descuento tributario"] },

  // ─── P ───
  { termino: "Paraiso fiscal", definicion: "Jurisdiccion con baja o nula tributacion, secreto bancario y falta de intercambio de informacion. El Gobierno colombiano publica la lista de paraisos fiscales periodicamente.", articulos: ["260-7"], relacionados: ["Jurisdiccion no cooperante", "Precios de transferencia"] },
  { termino: "Parafiscales", definicion: "Contribuciones obligatorias del empleador destinadas a SENA (2%), ICBF (3%) y Cajas de Compensacion Familiar (4%). Totalizan 9% sobre la nomina.", articulos: ["114-1"], relacionados: ["Exoneracion Art. 114-1", "Seguridad social"] },
  { termino: "Patrimonio bruto", definicion: "Valor total de los bienes y derechos del contribuyente al 31 de diciembre, antes de restar deudas. Incluye inmuebles, vehiculos, cuentas bancarias, inversiones y demas activos.", articulos: ["261", "262"], relacionados: ["Patrimonio liquido", "Valor patrimonial"] },
  { termino: "Patrimonio liquido", definicion: "Patrimonio bruto menos las deudas a cargo del contribuyente. Es la base para calcular la renta presuntiva (si aplica) y el impuesto al patrimonio.", articulos: ["282"], relacionados: ["Patrimonio bruto", "Renta presuntiva", "Impuesto al patrimonio"] },
  { termino: "Periodo gravable del IVA", definicion: "Periodo de liquidacion del IVA: bimestral (contribuyentes con ingresos > 92.000 UVT) o cuatrimestral (ingresos <= 92.000 UVT). Cada periodo se declara en el mes siguiente.", articulos: ["600", "601"], relacionados: ["IVA", "Responsable de IVA"] },
  { termino: "PILA", definicion: "Planilla Integrada de Liquidacion de Aportes. Formulario unico para pagar aportes a seguridad social (salud, pension, ARL) y parafiscales (SENA, ICBF, CCF).", relacionados: ["Seguridad social", "IBC", "Cotizante"] },
  { termino: "Precios de transferencia", definicion: "Regimen que obliga a contribuyentes con operaciones vinculadas del exterior a demostrar que sus precios son de mercado (principio de plena competencia). Obligatorio si patrimonio > 100.000 UVT o ingresos > 61.000 UVT.", articulos: ["260-1", "260-2", "260-3", "260-4"], relacionados: ["Jurisdiccion no cooperante", "Establecimiento permanente"] },
  { termino: "Principio de territorialidad", definicion: "Criterio segun el cual los residentes tributan sobre rentas mundiales mientras que los no residentes solo tributan sobre rentas de fuente colombiana.", articulos: ["9", "24", "25"], relacionados: ["Renta de fuente nacional", "Convenio de doble imposicion"] },
  { termino: "Procedimiento 1", definicion: "Metodo de retencion en la fuente por salarios que calcula la retencion mensualmente aplicando la tabla del Art. 383 sobre el ingreso laboral depurado.", articulos: ["385", "383"], relacionados: ["Procedimiento 2", "Depuracion", "Tabla Art. 383"] },
  { termino: "Procedimiento 2", definicion: "Metodo de retencion en la fuente por salarios que calcula un porcentaje fijo semestral basado en el promedio de pagos de los ultimos 12 meses.", articulos: ["386"], relacionados: ["Procedimiento 1", "Tabla Art. 383"] },
  { termino: "Prorrateo de IVA", definicion: "Metodo para distribuir el IVA descontable cuando el responsable realiza operaciones gravadas y excluidas simultaneamente. Solo se descuenta la proporcion correspondiente a las operaciones gravadas.", articulos: ["490"], relacionados: ["IVA descontable", "IVA generado"] },

  // ─── R ───
  { termino: "RADIAN", definicion: "Registro de Facturas Electronicas de Venta como Titulo Valor. Plataforma de la DIAN que permite negociar facturas electronicas como titulos valores (factoring).", relacionados: ["Factura electronica", "Titulo ejecutivo"] },
  { termino: "Recurso de reconsideracion", definicion: "Recurso administrativo que interpone el contribuyente contra liquidaciones oficiales y resoluciones de la DIAN. Plazo: 2 meses desde la notificacion. La DIAN tiene 1 ano para resolver.", articulos: ["720", "722", "726", "732"], relacionados: ["Liquidacion oficial", "Requerimiento especial"] },
  { termino: "Regimen tributario especial", definicion: "Regimen aplicable a ESAL (fundaciones, asociaciones, cooperativas) que cumplan requisitos de merito social. Tarifa del 20% sobre el beneficio neto o exencion si reinvierten.", articulos: ["356", "357", "358", "359"], relacionados: ["ESAL", "Donaciones"] },
  { termino: "Renta de fuente nacional", definicion: "Ingresos obtenidos de actividades o bienes ubicados en Colombia. Incluye servicios prestados en el pais, explotacion de bienes en territorio nacional y enajenacion de activos colombianos.", articulos: ["24", "25"], relacionados: ["Principio de territorialidad", "Establecimiento permanente"] },
  { termino: "Renta exenta", definicion: "Ingresos gravados a tarifa cero (0%) que se incluyen en la depuracion pero no generan impuesto. Incluye: 25% de ingresos laborales, aportes a AFC, pensiones hasta 12.000 UVT.", articulos: ["206", "207", "235-2"], relacionados: ["INCRNGO", "Deduccion", "Renta exenta del 25%"] },
  { termino: "Renta exenta del 25%", definicion: "El 25% de los ingresos laborales netos se considera renta exenta (Art. 206 num 10). Tope: 240 UVT mensuales (2.880 UVT anuales). Aplica dentro del limite del 40%.", articulos: ["206"], relacionados: ["Renta exenta", "Cedula general", "Limite del 40%"] },
  { termino: "Renta liquida gravable", definicion: "Resultado de restar a los ingresos netos las deducciones y rentas exentas permitidas. Es la base sobre la cual se aplica la tarifa del impuesto de renta.", articulos: ["178", "241", "336"], relacionados: ["Base gravable", "Deduccion", "Depuracion"] },
  { termino: "Renta ordinaria", definicion: "Ingresos habituales del contribuyente provenientes de su actividad economica principal: salarios, honorarios, arrendamientos, ventas, intereses, entre otros.", articulos: ["26"], relacionados: ["Ganancia ocasional", "Cedula general"] },
  { termino: "Renta presuntiva", definicion: "Renta minima del contribuyente calculada sobre su patrimonio liquido. Tarifa actual: 0% (desde el ano gravable 2021).", articulos: ["188", "189"], relacionados: ["Patrimonio liquido", "Renta ordinaria"] },
  { termino: "Responsable de IVA", definicion: "Persona natural o juridica obligada a cobrar, declarar y pagar el IVA. Las personas juridicas que vendan bienes gravados son responsables. Las personas naturales lo son si superan 3.500 UVT de ingresos.", articulos: ["437"], relacionados: ["No responsable de IVA", "IVA"] },
  { termino: "ReteICA", definicion: "Retencion del Impuesto de Industria y Comercio. Mecanismo de recaudo anticipado del ICA que practican compradores sobre pagos a proveedores por actividades gravadas en el municipio.", relacionados: ["ICA", "Retencion en la fuente"] },
  { termino: "Retencion en la fuente", definicion: "Mecanismo de recaudo anticipado del impuesto, mediante el cual el pagador (agente retenedor) descuenta un porcentaje del pago y lo traslada a la DIAN.", articulos: ["367", "368", "369"], relacionados: ["Agente retenedor", "Autorretencion", "Base minima de retencion"] },
  { termino: "Retencion por arrendamientos", definicion: "Retencion del 3.5% sobre pagos por arrendamiento de bienes muebles o inmuebles cuando el pago supere 27 UVT. Para personas no declarantes de renta puede ser del 4%.", articulos: ["401"], relacionados: ["Retencion en la fuente", "Base minima de retencion"] },
  { termino: "Retencion por compras", definicion: "Retencion del 2.5% (declarantes) o 3.5% (no declarantes) sobre compras de bienes que superen 27 UVT. Conceptos especiales como combustibles tienen tarifas diferentes.", articulos: ["401"], relacionados: ["Retencion en la fuente", "Base minima de retencion"] },
  { termino: "Retencion por honorarios", definicion: "Retencion del 10% u 11% sobre pagos por honorarios y comisiones cuando superen bases minimas. Si el beneficiario declara renta, aplica el 10%; si no declara, el 11%.", articulos: ["392"], relacionados: ["Retencion en la fuente", "Retencion por servicios"] },
  { termino: "Retencion por rendimientos financieros", definicion: "Retencion del 4% (CDT) o 7% (otros rendimientos) sobre intereses y demas rendimientos financieros. Los bancos actuan como agentes retenedores.", articulos: ["395", "396"], relacionados: ["Retencion en la fuente"] },
  { termino: "Retencion por servicios", definicion: "Retencion del 4% (declarantes) o 6% (no declarantes) sobre pagos por prestacion de servicios que superen 4 UVT. Incluye consultoria, asesoria, outsourcing, entre otros.", articulos: ["392"], relacionados: ["Retencion en la fuente", "Retencion por honorarios"] },
  { termino: "RUT", definicion: "Registro Unico Tributario. Documento de identificacion fiscal ante la DIAN que contiene la informacion tributaria del contribuyente: NIT, actividades economicas, responsabilidades y obligaciones.", articulos: ["555-2"], relacionados: ["NIT", "DIAN", "MUISCA"] },

  // ─── S ───
  { termino: "SAGRILAFT", definicion: "Sistema de Autogestion de Riesgos de Lavado de Activos y Financiacion del Terrorismo. Obligatorio para empresas con ingresos > 30.000 SMLMV o patrimonio > 30.000 SMLMV.", relacionados: ["Beneficiario final", "DIAN"] },
  { termino: "Saldo a favor", definicion: "Resultado cuando las retenciones, anticipos y pagos previos del contribuyente superan el impuesto a cargo. Puede solicitarse en devolucion o compensacion.", articulos: ["850", "815"], relacionados: ["Devolucion de saldos a favor", "Compensacion tributaria"] },
  { termino: "Sancion minima", definicion: "Valor minimo de cualquier sancion tributaria: 10 UVT ($523.740 en 2026). Ninguna sancion impuesta por la DIAN puede ser inferior a este monto.", articulos: ["639"], relacionados: ["Gradualidad de sanciones", "Sancion por extemporaneidad"] },
  { termino: "Sancion por correccion", definicion: "Sancion por corregir una declaracion: 10% del mayor valor a pagar o menor saldo a favor si se corrige voluntariamente. Sube al 20% si es despues de emplazamiento.", articulos: ["644"], relacionados: ["Correccion de la declaracion", "Emplazamiento para corregir"] },
  { termino: "Sancion por extemporaneidad", definicion: "Sancion por presentar declaraciones tributarias fuera del plazo legal. Con impuesto a pagar: 5% por mes de mora. Sin impuesto: 0.5% de ingresos o 1% de patrimonio.", articulos: ["641", "642"], relacionados: ["Sancion minima", "Gradualidad de sanciones"] },
  { termino: "Seguridad social", definicion: "Sistema obligatorio de proteccion social que incluye salud (12.5%), pension (16%), ARL (segun riesgo) y parafiscales (9%). Los aportes se pagan mensualmente a traves de la PILA.", relacionados: ["Aportes a salud", "Aportes a pension", "ARL", "PILA"] },
  { termino: "Servicio gravado con IVA", definicion: "Prestacion de servicios que genera IVA a la tarifa del 19%. Incluye consultoria, arrendamiento de bienes, transporte, servicios tecnologicos, entre otros.", articulos: ["420"], relacionados: ["IVA", "Bien gravado", "Tarifa general de IVA"] },
  { termino: "Silencio administrativo positivo", definicion: "Cuando la DIAN no resuelve dentro del plazo legal (ej. 6 meses para devolucion, 1 ano para recurso), se entiende que la decision es favorable al contribuyente.", articulos: ["732", "855"], relacionados: ["Recurso de reconsideracion", "Devolucion de saldos a favor"] },
  { termino: "SIMPLE", definicion: "Regimen Simple de Tributacion. Impuesto unificado que sustituye renta, IVA (para restaurantes), ICA e impuesto de consumo para contribuyentes con ingresos < 100.000 UVT.", articulos: ["903", "905", "908"], relacionados: ["ICA", "Impuesto Nacional al Consumo"] },
  { termino: "SMLMV", definicion: "Salario Minimo Legal Mensual Vigente. Remuneracion minima que debe recibir un trabajador por su labor en Colombia. Para 2026: $1,750,905.", relacionados: ["IBC", "Parafiscales", "UVT"] },
  { termino: "Sobretasa de renta", definicion: "Impuesto adicional al de renta para personas juridicas con renta liquida gravable superior a 120.000 UVT. Aplica desde 2023 (Ley 2277). Tarifa del 3% al 5% segun el rango.", articulos: ["240"], relacionados: ["Tarifa general personas juridicas", "Tasa de tributacion depurada"] },
  { termino: "Sociedad BIC", definicion: "Sociedad de Beneficio e Interes Colectivo. Persona juridica que ademas de buscar utilidad economica, persigue propositos de beneficio social y ambiental. No tiene tarifa diferencial en renta.", relacionados: ["ESAL", "Persona juridica"] },
  { termino: "Subcapitalizacion", definicion: "Limite a la deduccion de intereses pagados a vinculados economicos del exterior. Los intereses no son deducibles cuando la deuda exceda 2 veces el patrimonio liquido.", articulos: ["118-1"], relacionados: ["Precios de transferencia", "Deduccion"] },
  { termino: "Sujeto pasivo", definicion: "Persona natural o juridica obligada al cumplimiento de las obligaciones tributarias, ya sea en calidad de contribuyente o responsable.", relacionados: ["Contribuyente", "Responsable de IVA"] },

  // ─── T ───
  { termino: "Tabla Art. 241", definicion: "Tabla progresiva de tarifas para calcular el impuesto de renta de personas naturales residentes sobre la cedula general y pensiones. Rangos desde 0% hasta 39% segun la renta en UVT.", articulos: ["241"], relacionados: ["Cedula general", "Renta liquida gravable", "UVT"] },
  { termino: "Tabla Art. 383", definicion: "Tabla para calcular la retencion en la fuente sobre ingresos laborales (Procedimiento 1). Tiene los mismos rangos marginales que la tabla del Art. 241 pero aplicada mensualmente.", articulos: ["383"], relacionados: ["Procedimiento 1", "Retencion en la fuente"] },
  { termino: "Tarifa general de IVA", definicion: "Tarifa estandar del IVA en Colombia: 19%. Aplica a la venta de bienes y prestacion de servicios que no tengan tarifa diferencial (5%) ni esten exentos o excluidos.", articulos: ["468"], relacionados: ["IVA", "Bien gravado", "Bien exento de IVA"] },
  { termino: "Tarifa general personas juridicas", definicion: "Tarifa del impuesto sobre la renta para personas juridicas en el regimen ordinario: 35% desde el ano gravable 2022. Aplican tarifas diferenciales para zonas francas, ZOMAC y hoteles.", articulos: ["240"], relacionados: ["Sobretasa de renta", "Zona franca", "ZOMAC"] },
  { termino: "Tasa de tributacion depurada (TTD)", definicion: "Calculo que compara el impuesto efectivo del contribuyente con la tasa minima del 15% (Art. 240 par. 6). Si la TTD es menor, se debe pagar un impuesto adicional para alcanzar el 15%.", articulos: ["240"], relacionados: ["Tarifa general personas juridicas", "Sobretasa de renta"] },
  { termino: "Tasa efectiva de tributacion", definicion: "Relacion entre el impuesto de renta efectivamente pagado y los ingresos brutos del contribuyente. Permite medir la carga fiscal real, diferente de la tarifa nominal.", relacionados: ["Tarifa general personas juridicas", "Renta liquida gravable"] },
  { termino: "Titulo ejecutivo", definicion: "Documento que presta merito ejecutivo para el cobro coactivo: liquidaciones oficiales en firme, declaraciones con saldo a pagar, y otros actos administrativos que contengan una obligacion clara.", articulos: ["828"], relacionados: ["Facilidad de pago", "Liquidacion oficial"] },

  // ─── U ───
  { termino: "UVT", definicion: "Unidad de Valor Tributario. Medida de valor que permite ajustar los valores contenidos en las disposiciones tributarias. Para 2026: $52,374. Para 2025: $49,799.", articulos: ["868"], relacionados: ["Base gravable", "SMLMV"] },

  // ─── V ───
  { termino: "Valor patrimonial", definicion: "Valor fiscal asignado a cada activo y pasivo para efectos del impuesto de renta. Puede diferir del valor contable NIIF. Los inmuebles pueden declararse por el costo fiscal o el avaluo catastral, el mayor.", articulos: ["267", "268", "269", "277"], relacionados: ["Patrimonio bruto", "Costo fiscal", "Avaluo catastral"] },

  // ─── Z ───
  { termino: "ZESE", definicion: "Zonas Economicas y Sociales Especiales. Incentivo para empresas nuevas en departamentos como La Guajira, Norte de Santander y Arauca. Tarifa de renta del 0% los primeros 5 anos y 50% de la tarifa general los siguientes 5.", articulos: ["268-1"], relacionados: ["ZOMAC", "Zona franca", "Tarifa general personas juridicas"] },
  { termino: "ZOMAC", definicion: "Zonas Mas Afectadas por el Conflicto Armado. Incentivo para nuevas empresas en municipios priorizados. Tarifa progresiva: 0% a 25% durante 10 anos segun tamano de la empresa (micro, pequena, mediana, grande).", articulos: ["236", "237"], relacionados: ["ZESE", "Zona franca", "Obras por impuestos"] },
  { termino: "Zona franca", definicion: "Area geografica delimitada con tratamiento tributario especial. Tarifa de renta del 20%. Usuarios calificados deben cumplir requisitos de inversion y empleo. Tarifa de IVA 0% para exportaciones desde ZF.", articulos: ["240-1"], relacionados: ["Tarifa general personas juridicas", "Tasa de tributacion depurada", "ZESE"] },
];
