export interface DecisionNode {
  id: string;
  tipo: "pregunta" | "resultado";
  texto: string;
  opciones?: Array<{ label: string; nextNodeId: string }>;
  recomendacion?: string;
  enlaces?: Array<{ label: string; href: string }>;
  ayudaRapida?: string;
}

export interface GuiaEducativa {
  id: string;
  titulo: string;
  descripcion: string;
  categoria: "renta" | "iva" | "retencion" | "laboral" | "general";
  complejidad: "basica" | "intermedia" | "avanzada";
  nodos: DecisionNode[];
  nodoInicial: string;
}

export const GUIAS_EDUCATIVAS: GuiaEducativa[] = [
  {
    id: "declarar-renta",
    titulo: "¿Debo declarar renta?",
    descripcion: "Verifica si cumples los topes para declarar renta como persona natural en el año gravable 2025.",
    categoria: "renta",
    complejidad: "basica",
    nodoInicial: "residencia",
    nodos: [
      {
        id: "residencia",
        tipo: "pregunta",
        texto: "¿Eres residente fiscal en Colombia? (Permanencia > 183 días o familia/bienes en el país)",
        ayudaRapida: "La residencia fiscal no depende de la nacionalidad, sino de tu permanencia o vínculos económicos/familiares.",
        opciones: [
          { label: "Sí", nextNodeId: "patrimonio" },
          { label: "No", nextNodeId: "no-residente" },
        ],
      },
      {
        id: "patrimonio",
        tipo: "pregunta",
        texto: "¿Tu patrimonio bruto al 31 de dic de 2025 fue superior a 4.500 UVT ($224.095.500)?",
        ayudaRapida: "Suma tus bienes (casa, carro, ahorros, acciones) sin restar las deudas que tengas sobre ellos.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-declara" },
          { label: "No", nextNodeId: "ingresos" },
        ],
      },
      {
        id: "ingresos",
        tipo: "pregunta",
        texto: "¿Tus ingresos brutos en 2025 fueron superiores a 1.400 UVT ($69.718.600)?",
        ayudaRapida: "Incluye salarios, honorarios, arriendos, rendimientos financieros y pensiones recibidos en el año.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-declara" },
          { label: "No", nextNodeId: "tarjetas" },
        ],
      },
      {
        id: "tarjetas",
        tipo: "pregunta",
        texto: "¿Tus consumos con tarjeta de crédito superaron los 1.400 UVT ($69.718.600)?",
        ayudaRapida: "Suma todos los pagos realizados con tus tarjetas, incluso si son compras para terceros.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-declara" },
          { label: "No", nextNodeId: "consignaciones" },
        ],
      },
      {
        id: "consignaciones",
        tipo: "pregunta",
        texto: "¿El valor total de tus consignaciones o inversiones superó los 1.400 UVT ($69.718.600)?",
        ayudaRapida: "Cuenta todo el dinero que entró a tus cuentas bancarias, incluyendo préstamos o traslados.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-declara" },
          { label: "No", nextNodeId: "resultado-no-declara" },
        ],
      },
      {
        id: "no-residente",
        tipo: "resultado",
        texto: "Situación de No Residente",
        recomendacion: "Los no residentes solo declaran si su patrimonio en Colombia o sus ingresos de fuente nacional no fueron objeto de retención en la fuente (Art. 407 a 411 ET).",
        enlaces: [{ label: "Ver Estatuto Art. 9", href: "/explorador?art=9" }],
      },
      {
        id: "resultado-declara",
        tipo: "resultado",
        texto: "¡DEBES DECLARAR RENTA!",
        recomendacion: "Cumples con al menos uno de los topes legales. Recuerda que declarar no siempre significa pagar.",
        enlaces: [{ label: "Calendario Tributario", href: "/calendario" }],
      },
      {
        id: "resultado-no-declara",
        tipo: "resultado",
        texto: "No estás obligado a declarar",
        recomendacion: "No superas ninguno de los topes para el año gravable 2025. Sin embargo, puedes declarar voluntariamente si te practicaron retenciones.",
      },
    ],
  },
  {
    id: "simple-vs-ordinario",
    titulo: "SIMPLE vs Ordinario: ¿Cuál me conviene?",
    descripcion: "Analiza si te conviene migrar al Régimen Simple de Tributación o quedarte en Renta Ordinaria.",
    categoria: "general",
    complejidad: "intermedia",
    nodoInicial: "ingresos-tope",
    nodos: [
      {
        id: "ingresos-tope",
        tipo: "pregunta",
        texto: "¿Tus ingresos brutos anuales son inferiores a 100.000 UVT ($5.237.400.000)?",
        ayudaRapida: "Este es el tope general para pertenecer al SIMPLE para la mayoría de actividades empresariales.",
        opciones: [
          { label: "Sí", nextNodeId: "tipo-actividad" },
          { label: "No", nextNodeId: "ordinario-obligatorio" },
        ],
      },
      {
        id: "tipo-actividad",
        tipo: "pregunta",
        texto: "¿Tu actividad es de servicios profesionales (consultoría, profesiones liberales)?",
        ayudaRapida: "Las profesiones liberales tienen un tope de ingresos menor y tarifas diferentes en el SIMPLE.",
        opciones: [
          { label: "Sí", nextNodeId: "tope-profesionales" },
          { label: "No", nextNodeId: "costos-altos" },
        ],
      },
      {
        id: "tope-profesionales",
        tipo: "pregunta",
        texto: "¿Tus ingresos como profesional son inferiores a 12.000 UVT ($628.488.000)?",
        ayudaRapida: "Si superas este tope como profesional, el SIMPLE deja de ser una opción legal por sentencia de la Corte.",
        opciones: [
          { label: "Sí", nextNodeId: "costos-altos" },
          { label: "No", nextNodeId: "ordinario-mejor-prof" },
        ],
      },
      {
        id: "costos-altos",
        tipo: "pregunta",
        texto: "¿Tus costos y gastos reales superan el 70% de tus ingresos?",
        ayudaRapida: "Como el SIMPLE paga sobre ingresos brutos, si tienes costos muy altos podrías terminar pagando más impuesto.",
        opciones: [
          { label: "Sí", nextNodeId: "ordinario-mejor-costos" },
          { label: "No", nextNodeId: "nomina-empleados" },
        ],
      },
      {
        id: "nomina-empleados",
        tipo: "pregunta",
        texto: "¿Tienes empleados por nómina con aportes a pensión?",
        ayudaRapida: "En el SIMPLE puedes descontar el 100% de tus aportes a pensión de tus empleados del impuesto a pagar.",
        opciones: [
          { label: "Sí", nextNodeId: "simple-ideal" },
          { label: "No", nextNodeId: "simple-conveniente" },
        ],
      },
      {
        id: "ordinario-obligatorio",
        tipo: "resultado",
        texto: "Régimen Ordinario Obligatorio",
        recomendacion: "Superas el tope máximo para el SIMPLE. Debes declarar bajo el régimen ordinario.",
      },
      {
        id: "ordinario-mejor-prof",
        tipo: "resultado",
        texto: "Se recomienda Ordinario",
        recomendacion: "Los profesionales con ingresos > 12.000 UVT suelen tener una carga mayor en el SIMPLE tras la Sentencia C-540 de 2023.",
      },
      {
        id: "ordinario-mejor-costos",
        tipo: "resultado",
        texto: "Mejor Ordinario (por costos)",
        recomendacion: "Dado que el SIMPLE grava ingresos brutos y no permite restar costos, con gastos > 70% es probable que la renta ordinaria sea más barata.",
        enlaces: [{ label: "Calculadora SIMPLE", href: "/calculadoras/simple" }],
      },
      {
        id: "simple-ideal",
        tipo: "resultado",
        texto: "¡El SIMPLE es ideal para ti!",
        recomendacion: "Puedes descontar los aportes a pensión de tus empleados y simplificar 7 impuestos en uno. Tu ahorro será significativo.",
        enlaces: [{ label: "Calculadora SIMPLE", href: "/calculadoras/simple" }],
      },
      {
        id: "simple-conveniente",
        tipo: "resultado",
        texto: "SIMPLE es conveniente",
        recomendacion: "Aunque no tengas nómina, las tarifas bajas del SIMPLE sobre ingresos brutos suelen ser menores que la tarifa del ordinario sobre utilidad.",
      },
    ],
  },
  {
    id: "responsable-iva",
    titulo: "¿Soy responsable de IVA?",
    descripcion: "Determina si debes inscribirte como responsable de IVA o puedes operar como no responsable.",
    categoria: "iva",
    complejidad: "basica",
    nodoInicial: "ingresos-3500",
    nodos: [
      {
        id: "ingresos-3500",
        tipo: "pregunta",
        texto: "¿Tus ingresos brutos por actividades gravadas en 2024 o 2025 superaron los 3.500 UVT ($174.296.500)?",
        ayudaRapida: "Suma solo los ingresos que provienen de bienes o servicios que tienen IVA (la mayoría, salvo excepciones).",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-si-iva" },
          { label: "No", nextNodeId: "establecimientos" },
        ],
      },
      {
        id: "establecimientos",
        tipo: "pregunta",
        texto: "¿Tienes más de un establecimiento de comercio, oficina o local?",
        ayudaRapida: "Tener dos locales abiertos al público te obliga automáticamente a ser responsable de IVA.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-si-iva" },
          { label: "No", nextNodeId: "franquicias" },
        ],
      },
      {
        id: "franquicias",
        tipo: "pregunta",
        texto: "¿Desarrollas actividades bajo franquicia, marca o concesión?",
        ayudaRapida: "Si tu negocio es una franquicia (ej. Servientrega, cosecha, etc.), eres responsable de IVA.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-si-iva" },
          { label: "No", nextNodeId: "aduana" },
        ],
      },
      {
        id: "aduana",
        tipo: "pregunta",
        texto: "¿Eres usuario aduanero?",
        ayudaRapida: "Si realizas importaciones o exportaciones formales ante la DIAN, sueles ser responsable de IVA.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-si-iva" },
          { label: "No", nextNodeId: "consignaciones-iva" },
        ],
      },
      {
        id: "consignaciones-iva",
        tipo: "pregunta",
        texto: "¿Tus consignaciones bancarias en el año superaron los 3.500 UVT?",
        ayudaRapida: "Al igual que en renta, mover más de $174 millones en tus cuentas te obliga a recaudar IVA.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-si-iva" },
          { label: "No", nextNodeId: "resultado-no-iva" },
        ],
      },
      {
        id: "resultado-si-iva",
        tipo: "resultado",
        texto: "Eres RESPONSABLE de IVA",
        recomendacion: "Debes inscribirte en el RUT como responsable de IVA, facturar electrónicamente y presentar declaraciones bimestrales o cuatrimestrales.",
        enlaces: [{ label: "Ver Art. 437 ET", href: "/explorador?art=437" }],
      },
      {
        id: "resultado-no-iva",
        tipo: "resultado",
        texto: "No eres responsable de IVA",
        recomendacion: "Puedes operar como no responsable. Asegúrate de no superar los topes en el transcurso del año.",
      },
    ],
  },
  {
    id: "sanciones-dian",
    titulo: "¿Qué sanciones aplican a mi caso?",
    descripcion: "Evalúa las posibles sanciones por extemporaneidad o corrección.",
    categoria: "general",
    complejidad: "basica",
    nodoInicial: "tipo-falta",
    nodos: [
      {
        id: "tipo-falta",
        tipo: "pregunta",
        texto: "¿Cuál es tu situación actual?",
        ayudaRapida: "Identifica si el error es por tiempo (presentar tarde) o por contenido (corregir datos).",
        opciones: [
          { label: "No presenté la declaración a tiempo", nextNodeId: "pago-previo" },
          { label: "Debo corregir una declaración ya presentada", nextNodeId: "aumenta-impuesto" },
        ],
      },
      {
        id: "pago-previo",
        tipo: "pregunta",
        texto: "¿La declaración arroja un impuesto a pagar?",
        ayudaRapida: "Si la declaración da saldo a favor, la sanción suele calcularse sobre ingresos o patrimonio.",
        opciones: [
          { label: "Sí", nextNodeId: "extemporaneidad-con-pago" },
          { label: "No", nextNodeId: "extemporaneidad-sin-pago" },
        ],
      },
      {
        id: "aumenta-impuesto",
        tipo: "pregunta",
        texto: "¿La corrección aumenta el impuesto o disminuye el saldo a favor?",
        ayudaRapida: "Corregir para pagar más genera sanción; corregir para pagar menos no (pero requiere proceso especial).",
        opciones: [
          { label: "Sí", nextNodeId: "sancion-correccion" },
          { label: "No", nextNodeId: "sin-sancion-correccion" },
        ],
      },
      {
        id: "extemporaneidad-con-pago",
        tipo: "resultado",
        texto: "Sanción por Extemporaneidad",
        recomendacion: "5% del impuesto por cada mes o fracción de retraso, sin exceder el 100%. Mínimo $47.000 (10 UVT).",
        enlaces: [{ label: "Calculadora de Intereses", href: "/calculadoras/intereses-mora" }],
      },
      {
        id: "extemporaneidad-sin-pago",
        tipo: "resultado",
        texto: "Sanción sobre Ingresos o Patrimonio",
        recomendacion: "0.5% de los ingresos brutos por cada mes de retraso. Si no hay ingresos, 1% del patrimonio líquido.",
      },
      {
        id: "sancion-correccion",
        tipo: "resultado",
        texto: "Sanción por Corrección",
        recomendacion: "10% del mayor valor a pagar o del menor saldo a favor, antes del emplazamiento para corregir.",
      },
      {
        id: "sin-sancion-correccion",
        tipo: "resultado",
        texto: "Corrección sin sanción",
        recomendacion: "Si la corrección no varía el impuesto o es para aumentar el saldo a favor, no hay sanción (salvo casos específicos de procesos de fiscalización).",
      },
    ],
  },
  {
    id: "retencion-salarios",
    titulo: "¿Cómo calculo mi retención por salarios?",
    descripcion: "Entiende paso a paso cómo se calcula la retención en la fuente sobre tus ingresos laborales.",
    categoria: "retencion",
    complejidad: "intermedia",
    nodoInicial: "tipo-vinculacion",
    nodos: [
      {
        id: "tipo-vinculacion",
        tipo: "pregunta",
        texto: "¿Recibes tus ingresos como asalariado o como trabajador independiente?",
        ayudaRapida: "Los asalariados tienen un sistema de depuración mensual; los independientes pueden tener costos o tabla del 383.",
        opciones: [
          { label: "Asalariado (contrato laboral)", nextNodeId: "procedimiento" },
          { label: "Independiente (prestación de servicios)", nextNodeId: "resultado-independiente" },
        ],
      },
      {
        id: "resultado-independiente",
        tipo: "resultado",
        texto: "Retención para independientes",
        recomendacion: "Como independiente, si tus ingresos del año anterior superaron 3.300 UVT te aplica la tabla del Art. 383 ET. De lo contrario, retención ordinaria del 10% u 11%.",
        enlaces: [
          { label: "Calculadora de Retención", href: "/calculadoras/retencion" },
          { label: "Tablas de Retención", href: "/tablas/retencion" },
        ],
      },
      {
        id: "procedimiento",
        tipo: "pregunta",
        texto: "¿Tu empleador aplica el Procedimiento 1 o el Procedimiento 2?",
        ayudaRapida: "El P1 es mensual fijo; el P2 usa un porcentaje que cambia cada 6 meses (en junio y diciembre).",
        opciones: [
          { label: "Procedimiento 1 (depuración mensual)", nextNodeId: "dependientes" },
          { label: "Procedimiento 2 (porcentaje fijo semestral)", nextNodeId: "resultado-p2" },
          { label: "No sé cuál me aplica", nextNodeId: "dependientes" },
        ],
      },
      {
        id: "dependientes",
        tipo: "pregunta",
        texto: "¿Tienes personas a cargo (dependientes económicos)?",
        ayudaRapida: "Hijos menores de 18 (o hasta 23 si estudian), cónyuge o padres sin ingresos propios.",
        opciones: [
          { label: "Sí, tengo dependientes", nextNodeId: "aportes-voluntarios" },
          { label: "No tengo dependientes", nextNodeId: "resultado-p1-basico" },
        ],
      },
      {
        id: "aportes-voluntarios",
        tipo: "pregunta",
        texto: "¿Realizas aportes voluntarios a pensión o cuentas AFC?",
        ayudaRapida: "Ahorrar en fondos de pensiones voluntarias o cuentas de vivienda reduce tu base de retención.",
        opciones: [
          { label: "Sí, hago aportes voluntarios", nextNodeId: "resultado-p1-completo" },
          { label: "No realizo aportes voluntarios", nextNodeId: "resultado-p1-basico" },
        ],
      },
      {
        id: "resultado-p1-basico",
        tipo: "resultado",
        texto: "Retención por Procedimiento 1",
        recomendacion: "Tu empleador calcula la retención mensualmente: toma tu ingreso laboral, resta aportes obligatorios a salud y pensión, aplica deducciones y la renta exenta del 25%, y aplica la tabla del Art. 383 ET.",
        enlaces: [
          { label: "Calculadora Retención Salarios", href: "/calculadoras/retencion-salarios" },
          { label: "Calculadora de Retención General", href: "/calculadoras/retencion" },
        ],
      },
      {
        id: "resultado-p1-completo",
        tipo: "resultado",
        texto: "Retención P1 con beneficios tributarios",
        recomendacion: "Tienes varios beneficios que reducen tu retención: deducción por dependientes (hasta 72 UVT), aportes voluntarios a pensión/AFC (renta exenta hasta 30%) y la renta exenta general del 25%. Recuerda que rentas exentas + deducciones no pueden superar el 40% del ingreso neto.",
        enlaces: [
          { label: "Calculadora Retención Salarios", href: "/calculadoras/retencion-salarios" },
          { label: "Tablas de Retención", href: "/tablas/retencion" },
        ],
      },
      {
        id: "resultado-p2",
        tipo: "resultado",
        texto: "Retención por Procedimiento 2",
        recomendacion: "Se aplica un porcentaje fijo calculado semestralmente. El porcentaje se determina dividiendo la retención teórica de los 12 meses anteriores entre los pagos gravables del mismo período. Consulta con tu empleador el porcentaje vigente.",
        enlaces: [
          { label: "Calculadora Retención Salarios", href: "/calculadoras/retencion-salarios" },
          { label: "Calculadora de Retención General", href: "/calculadoras/retencion" },
        ],
      },
    ],
  },
  {
    id: "regimen-iva",
    titulo: "¿Qué régimen de IVA me aplica?",
    descripcion: "Determina si eres responsable de IVA, no responsable, o si te aplica el SIMPLE con IVA integrado.",
    categoria: "iva",
    complejidad: "intermedia",
    nodoInicial: "actividad-gravada",
    nodos: [
      {
        id: "actividad-gravada",
        tipo: "pregunta",
        texto: "¿Vendes bienes o prestas servicios gravados con IVA?",
        ayudaRapida: "La mayoría de bienes en Colombia tienen IVA del 19%. Algunos son exentos (tarifa 0) o excluidos.",
        opciones: [
          { label: "Sí, vendo bienes/servicios gravados", nextNodeId: "tipo-persona" },
          { label: "No, solo excluidos o exentos", nextNodeId: "resultado-no-responsable" },
        ],
      },
      {
        id: "resultado-no-responsable",
        tipo: "resultado",
        texto: "No eres responsable de IVA",
        recomendacion: "Si únicamente vendes bienes excluidos o exentos de IVA, no eres responsable de este impuesto.",
        enlaces: [{ label: "Calculadora de IVA", href: "/calculadoras/iva" }],
      },
      {
        id: "tipo-persona",
        tipo: "pregunta",
        texto: "¿Eres persona natural o persona jurídica?",
        ayudaRapida: "Las empresas (SAS, Ltda, etc.) suelen ser responsables de IVA por el solo hecho de ser personas jurídicas.",
        opciones: [
          { label: "Persona natural", nextNodeId: "ingresos-iva" },
          { label: "Persona jurídica", nextNodeId: "resultado-responsable-pj" },
        ],
      },
      {
        id: "resultado-responsable-pj",
        tipo: "resultado",
        texto: "Eres responsable de IVA",
        recomendacion: "Todas las personas jurídicas que vendan bienes o presten servicios gravados son responsables de IVA. Debes facturar con IVA y presentar declaración bimestral o cuatrimestral.",
        enlaces: [{ label: "Calculadora de IVA", href: "/calculadoras/iva" }],
      },
      {
        id: "ingresos-iva",
        tipo: "pregunta",
        texto: "¿Tus ingresos brutos del año anterior superaron 3.500 UVT ($174.296.500)?",
        ayudaRapida: "Este es el tope de ingresos para personas naturales; superarlo te obliga a cobrar IVA.",
        opciones: [
          { label: "Sí, los superaron", nextNodeId: "resultado-responsable-ingresos" },
          { label: "No, fueron menores", nextNodeId: "varios-locales" },
        ],
      },
      {
        id: "resultado-responsable-ingresos",
        tipo: "resultado",
        texto: "Eres responsable de IVA por ingresos",
        recomendacion: "Al superar los 3.500 UVT de ingresos debes inscribirte como responsable de IVA.",
        enlaces: [{ label: "Calculadora de IVA", href: "/calculadoras/iva" }],
      },
      {
        id: "varios-locales",
        tipo: "pregunta",
        texto: "¿Tienes más de un establecimiento de comercio u oficina?",
        ayudaRapida: "Incluso si ganas poco, tener dos locales te obliga a ser responsable de IVA.",
        opciones: [
          { label: "Sí, tengo más de uno", nextNodeId: "resultado-responsable-locales" },
          { label: "No, solo uno o ninguno", nextNodeId: "en-simple" },
        ],
      },
      {
        id: "resultado-responsable-locales",
        tipo: "resultado",
        texto: "Eres responsable de IVA por establecimientos",
        recomendacion: "Al tener más de un establecimiento de comercio estás obligado como responsable de IVA.",
        enlaces: [{ label: "Calculadora de IVA", href: "/calculadoras/iva" }],
      },
      {
        id: "en-simple",
        tipo: "pregunta",
        texto: "¿Estás inscrito en el Régimen SIMPLE de Tributación?",
        ayudaRapida: "El SIMPLE simplifica el recaudo de IVA pero tiene reglas especiales para peluquerías y restaurantes.",
        opciones: [
          { label: "Sí, estoy en el SIMPLE", nextNodeId: "resultado-simple-iva" },
          { label: "No", nextNodeId: "resultado-no-responsable-cumple" },
        ],
      },
      {
        id: "resultado-simple-iva",
        tipo: "resultado",
        texto: "Régimen SIMPLE con IVA incluido",
        recomendacion: "En el SIMPLE, el IVA se integra en la tarifa unificada. No presentas declaración de IVA por separado.",
        enlaces: [
          { label: "Calculadora SIMPLE", href: "/calculadoras/simple" },
          { label: "Comparador de Regímenes", href: "/calculadoras/comparador-regimenes" },
        ],
      },
      {
        id: "resultado-no-responsable-cumple",
        tipo: "resultado",
        texto: "No eres responsable de IVA",
        recomendacion: "Cumples los requisitos del Art. 437 par. 3 ET para NO ser responsable. No debes cobrar IVA en tus ventas.",
        enlaces: [{ label: "Calculadora de IVA", href: "/calculadoras/iva" }],
      },
    ],
  },
  {
    id: "impuesto-patrimonio",
    titulo: "¿Debo pagar impuesto al patrimonio?",
    descripcion: "Determina si estás sujeto al impuesto al patrimonio según tu patrimonio líquido y residencia fiscal.",
    categoria: "renta",
    complejidad: "basica",
    nodoInicial: "es-persona-natural",
    nodos: [
      {
        id: "es-persona-natural",
        tipo: "pregunta",
        texto: "¿Eres persona natural?",
        ayudaRapida: "Este impuesto aplica principalmente a personas naturales y sucesiones ilíquidas con altos patrimonios.",
        opciones: [
          { label: "Sí, soy persona natural", nextNodeId: "patrimonio-72k" },
          { label: "No, soy persona jurídica", nextNodeId: "resultado-no-aplica-pj" },
        ],
      },
      {
        id: "resultado-no-aplica-pj",
        tipo: "resultado",
        texto: "No aplica impuesto al patrimonio",
        recomendacion: "Las personas jurídicas nacionales no son sujetas del impuesto al patrimonio. Si eres entidad extranjera con bienes en Colombia, consulta con un profesional.",
        enlaces: [{ label: "Calculadora de Patrimonio", href: "/calculadoras/patrimonio" }],
      },
      {
        id: "patrimonio-72k",
        tipo: "pregunta",
        texto: "¿Tu patrimonio líquido al 1 de enero supera las 72.000 UVT ($3.771 millones)?",
        ayudaRapida: "Patrimonio líquido = Bienes totales menos deudas totales.",
        opciones: [
          { label: "Sí, supera 72.000 UVT", nextNodeId: "residencia-fiscal" },
          { label: "No, es menor", nextNodeId: "resultado-no-aplica-tope" },
        ],
      },
      {
        id: "resultado-no-aplica-tope",
        tipo: "resultado",
        texto: "No debes pagar impuesto al patrimonio",
        recomendacion: "Si tu patrimonio líquido no supera las 72.000 UVT, no estás sujeto al impuesto al patrimonio.",
        enlaces: [
          { label: "Calculadora de Patrimonio", href: "/calculadoras/patrimonio" },
          { label: "Conversor de UVT", href: "/calculadoras/uvt" },
        ],
      },
      {
        id: "residencia-fiscal",
        tipo: "pregunta",
        texto: "¿Eres residente fiscal colombiano?",
        ayudaRapida: "Si eres residente, pagas sobre tus bienes en todo el mundo. Si no, solo sobre tus bienes en Colombia.",
        opciones: [
          { label: "Sí, soy residente fiscal", nextNodeId: "resultado-debe-pagar-residente" },
          { label: "No, soy no residente", nextNodeId: "resultado-debe-pagar-no-residente" },
        ],
      },
      {
        id: "resultado-debe-pagar-residente",
        tipo: "resultado",
        texto: "Sí, debes pagar impuesto al patrimonio",
        recomendacion: "Como residente fiscal con patrimonio líquido superior a 72.000 UVT, debes pagar sobre tu patrimonio mundial. Tarifa progresiva: 0.5% (72K-122K UVT), 1% (122K-239K UVT) y 1.5% (exceso de 239K UVT).",
        enlaces: [{ label: "Calculadora de Patrimonio", href: "/calculadoras/patrimonio" }],
      },
      {
        id: "resultado-debe-pagar-no-residente",
        tipo: "resultado",
        texto: "Debes pagar sobre patrimonio en Colombia",
        recomendacion: "Como no residente con patrimonio en Colombia superior a 72.000 UVT, debes pagar solo sobre los bienes que poseas en Colombia. Las tarifas son las mismas que para residentes.",
        enlaces: [{ label: "Calculadora de Patrimonio", href: "/calculadoras/patrimonio" }],
      },
    ],
  },
  {
    id: "facturacion-electronica",
    titulo: "¿Necesito facturar electrónicamente?",
    descripcion: "Determina si estás obligado a emitir factura electrónica de venta según la normativa vigente.",
    categoria: "general",
    complejidad: "basica",
    nodoInicial: "tipo-persona-fe",
    nodos: [
      {
        id: "tipo-persona-fe",
        tipo: "pregunta",
        texto: "¿Eres persona natural o persona jurídica?",
        ayudaRapida: "Las personas jurídicas (SAS, Ltda, SA) están obligadas en casi todos los casos. Las personas naturales dependen de sus ingresos y actividad.",
        opciones: [
          { label: "Persona natural", nextNodeId: "actividad-gravada-fe" },
          { label: "Persona jurídica", nextNodeId: "resultado-obligado-pj" },
        ],
      },
      {
        id: "resultado-obligado-pj",
        tipo: "resultado",
        texto: "Sí, debes facturar electrónicamente",
        recomendacion: "Todas las personas jurídicas que vendan bienes o presten servicios deben emitir factura electrónica de venta validada por la DIAN. Debes habilitarte en el sistema de facturación de la DIAN.",
        enlaces: [{ label: "Ver Art. 616-1 ET", href: "/explorador?art=616-1" }],
      },
      {
        id: "actividad-gravada-fe",
        tipo: "pregunta",
        texto: "¿Vendes bienes o prestas servicios gravados con IVA?",
        ayudaRapida: "Si tu actividad genera IVA (tarifa 19% o 5%), generalmente estás obligado a facturar.",
        opciones: [
          { label: "Sí, vendo bienes/servicios gravados", nextNodeId: "ingresos-fe" },
          { label: "No, solo excluidos o exentos", nextNodeId: "regimen-simple-fe" },
        ],
      },
      {
        id: "ingresos-fe",
        tipo: "pregunta",
        texto: "¿Tus ingresos brutos del año anterior superaron 3.500 UVT ($174.296.500)?",
        ayudaRapida: "Este es el tope para ser responsable de IVA y, por tanto, obligado a facturar electrónicamente.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-obligado-ingresos" },
          { label: "No", nextNodeId: "resultado-no-obligado" },
        ],
      },
      {
        id: "regimen-simple-fe",
        tipo: "pregunta",
        texto: "¿Estás inscrito en el Régimen SIMPLE?",
        ayudaRapida: "Los contribuyentes del SIMPLE también deben facturar electrónicamente.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-obligado-simple" },
          { label: "No", nextNodeId: "resultado-no-obligado" },
        ],
      },
      {
        id: "resultado-obligado-ingresos",
        tipo: "resultado",
        texto: "Sí, debes facturar electrónicamente",
        recomendacion: "Al superar 3.500 UVT de ingresos eres responsable de IVA y debes facturar electrónicamente. Habilítate en el portal de la DIAN.",
        enlaces: [{ label: "Ver Art. 616-1 ET", href: "/explorador?art=616-1" }],
      },
      {
        id: "resultado-obligado-simple",
        tipo: "resultado",
        texto: "Sí, debes facturar electrónicamente",
        recomendacion: "Los contribuyentes del SIMPLE están obligados a facturar electrónicamente sin importar el monto de ingresos.",
      },
      {
        id: "resultado-no-obligado",
        tipo: "resultado",
        texto: "No estás obligado a facturar electrónicamente",
        recomendacion: "Como persona natural no responsable de IVA con ingresos inferiores a 3.500 UVT, no estás obligado. Sin embargo, puedes facturar voluntariamente si lo necesitas para tus clientes.",
      },
    ],
  },
  {
    id: "corregir-declaracion",
    titulo: "¿Cómo corrijo mi declaración?",
    descripcion: "Conoce el procedimiento correcto para corregir una declaración tributaria ya presentada ante la DIAN.",
    categoria: "general",
    complejidad: "intermedia",
    nodoInicial: "tipo-correccion",
    nodos: [
      {
        id: "tipo-correccion",
        tipo: "pregunta",
        texto: "¿La corrección aumenta o disminuye el impuesto a pagar?",
        ayudaRapida: "Si descubriste que debes pagar más, se corrige por Art. 588. Si debes pagar menos (o aumentar tu saldo a favor), aplica Art. 589.",
        opciones: [
          { label: "Aumenta el impuesto (debo pagar más)", nextNodeId: "firmeza-aumenta" },
          { label: "Disminuye el impuesto (debo pagar menos)", nextNodeId: "firmeza-disminuye" },
          { label: "No cambia el impuesto (solo datos informativos)", nextNodeId: "resultado-sin-sancion" },
        ],
      },
      {
        id: "firmeza-aumenta",
        tipo: "pregunta",
        texto: "¿Ya recibiste emplazamiento para corregir de la DIAN?",
        ayudaRapida: "Si la DIAN ya te envió un emplazamiento, la sanción sube del 10% al 20%. Es mejor corregir antes.",
        opciones: [
          { label: "No, corrijo voluntariamente", nextNodeId: "resultado-correccion-voluntaria" },
          { label: "Sí, ya me emplazaron", nextNodeId: "resultado-correccion-emplazamiento" },
        ],
      },
      {
        id: "firmeza-disminuye",
        tipo: "pregunta",
        texto: "¿Han pasado menos de 12 meses desde el vencimiento del plazo para declarar?",
        ayudaRapida: "La corrección para disminuir el impuesto solo puede hacerse dentro del año siguiente al vencimiento. Después, solo por vía judicial.",
        opciones: [
          { label: "Sí, estoy dentro del plazo", nextNodeId: "resultado-correccion-589" },
          { label: "No, ya pasó más de un año", nextNodeId: "resultado-fuera-plazo" },
        ],
      },
      {
        id: "resultado-correccion-voluntaria",
        tipo: "resultado",
        texto: "Corrección voluntaria (Art. 588)",
        recomendacion: "Presenta la corrección por MUISCA pagando el mayor impuesto más sanción del 10% del mayor valor a pagar. Aplica gradualidad del Art. 640: puedes reducir la sanción al 75% si pagas todo al corregir.",
        enlaces: [
          { label: "Ver Art. 588 ET", href: "/explorador?art=588" },
          { label: "Calculadora de Intereses", href: "/calculadoras/intereses-mora" },
        ],
      },
      {
        id: "resultado-correccion-emplazamiento",
        tipo: "resultado",
        texto: "Corrección después de emplazamiento",
        recomendacion: "La sanción sube al 20% del mayor valor a pagar. Tienes 1 mes desde el emplazamiento para corregir. Si no corriges, la DIAN puede proferir liquidación oficial.",
        enlaces: [{ label: "Ver Art. 644 ET", href: "/explorador?art=644" }],
      },
      {
        id: "resultado-correccion-589",
        tipo: "resultado",
        texto: "Corrección para disminuir impuesto (Art. 589)",
        recomendacion: "Presenta solicitud de corrección ante la DIAN (no directamente en MUISCA). La DIAN tiene 6 meses para pronunciarse. Si no responde, aplica silencio administrativo positivo.",
        enlaces: [{ label: "Ver Art. 589 ET", href: "/explorador?art=589" }],
      },
      {
        id: "resultado-fuera-plazo",
        tipo: "resultado",
        texto: "Fuera de plazo para corrección",
        recomendacion: "Después de 1 año del vencimiento solo puedes buscar la revocatoria directa o acudir a la vía judicial (demanda ante el Tribunal Administrativo). Consulta con un abogado tributarista.",
      },
      {
        id: "resultado-sin-sancion",
        tipo: "resultado",
        texto: "Corrección sin sanción",
        recomendacion: "Si la corrección no varía el impuesto a pagar ni el saldo a favor (solo datos informativos como dirección, actividad económica), puedes corregir sin sanción dentro del plazo de firmeza.",
        enlaces: [{ label: "Ver Art. 588 ET", href: "/explorador?art=588" }],
      },
    ],
  },
  {
    id: "deducciones-personas-naturales",
    titulo: "¿Qué puedo deducir como persona natural?",
    descripcion: "Identifica las deducciones y rentas exentas que puedes aplicar para reducir tu impuesto de renta.",
    categoria: "renta",
    complejidad: "intermedia",
    nodoInicial: "tipo-ingreso-ded",
    nodos: [
      {
        id: "tipo-ingreso-ded",
        tipo: "pregunta",
        texto: "¿Tu principal fuente de ingresos es laboral (salario) o independiente (honorarios/servicios)?",
        ayudaRapida: "Los asalariados tienen beneficios automáticos como la renta exenta del 25%. Los independientes pueden restar costos y gastos reales.",
        opciones: [
          { label: "Asalariado (contrato laboral)", nextNodeId: "dependientes-ded" },
          { label: "Independiente (honorarios/servicios)", nextNodeId: "costos-independiente" },
        ],
      },
      {
        id: "dependientes-ded",
        tipo: "pregunta",
        texto: "¿Tienes personas a cargo (hijos menores, cónyuge sin ingresos, padres dependientes)?",
        ayudaRapida: "La deducción por dependientes es del 10% del ingreso bruto, con tope de 72 UVT mensuales ($3.770.928 en 2026).",
        opciones: [
          { label: "Sí, tengo dependientes", nextNodeId: "vivienda-ded" },
          { label: "No tengo dependientes", nextNodeId: "vivienda-ded" },
        ],
      },
      {
        id: "costos-independiente",
        tipo: "pregunta",
        texto: "¿Llevas contabilidad formal o prefieres usar la renta exenta del 25%?",
        ayudaRapida: "Los independientes pueden optar por restar costos reales (con soportes) o usar la renta exenta del 25% sin necesidad de soportar costos.",
        opciones: [
          { label: "Tengo costos y gastos con soporte", nextNodeId: "vivienda-ded" },
          { label: "Prefiero la renta exenta del 25%", nextNodeId: "vivienda-ded" },
        ],
      },
      {
        id: "vivienda-ded",
        tipo: "pregunta",
        texto: "¿Pagas intereses de crédito hipotecario o leasing habitacional?",
        ayudaRapida: "Puedes deducir hasta 100 UVT mensuales ($5.237.400) en intereses de vivienda. También aplican aportes a cuentas AFC.",
        opciones: [
          { label: "Sí, pago intereses de vivienda", nextNodeId: "aportes-vol-ded" },
          { label: "No", nextNodeId: "aportes-vol-ded" },
        ],
      },
      {
        id: "aportes-vol-ded",
        tipo: "pregunta",
        texto: "¿Haces aportes voluntarios a pensión o cuentas AFC?",
        ayudaRapida: "Los aportes a pensiones voluntarias y AFC son renta exenta hasta el 30% del ingreso. Son la mejor herramienta de planeación tributaria.",
        opciones: [
          { label: "Sí", nextNodeId: "resultado-deducciones-completas" },
          { label: "No", nextNodeId: "resultado-deducciones-basicas" },
        ],
      },
      {
        id: "resultado-deducciones-completas",
        tipo: "resultado",
        texto: "Tienes múltiples beneficios tributarios",
        recomendacion: "Puedes aplicar: renta exenta del 25% (hasta 2.880 UVT/año), dependientes (hasta 72 UVT/mes), intereses de vivienda (hasta 1.200 UVT/año), aportes voluntarios (hasta 30% del ingreso), medicina prepagada (hasta 192 UVT/año). IMPORTANTE: la suma de rentas exentas + deducciones no puede superar el 40% del ingreso neto (máx. 5.040 UVT).",
        enlaces: [
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
          { label: "Ver Art. 336 ET (límite 40%)", href: "/explorador?art=336" },
        ],
      },
      {
        id: "resultado-deducciones-basicas",
        tipo: "resultado",
        texto: "Beneficios tributarios básicos",
        recomendacion: "Sin aportes voluntarios, tus principales beneficios son: renta exenta del 25% (automática), aportes obligatorios a pensión y salud (INCRNGO), dependientes si aplica, e intereses de vivienda. Considera hacer aportes voluntarios a pensión para optimizar tu declaración.",
        enlaces: [
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
          { label: "Ver Art. 206 ET", href: "/explorador?art=206" },
        ],
      },
    ],
  },
  {
    id: "dividendos-tributacion",
    titulo: "¿Cómo tributan mis dividendos?",
    descripcion: "Entiende el tratamiento fiscal de los dividendos según tu tipo de contribuyente y el origen de las utilidades.",
    categoria: "renta",
    complejidad: "avanzada",
    nodoInicial: "tipo-persona-div",
    nodos: [
      {
        id: "tipo-persona-div",
        tipo: "pregunta",
        texto: "¿Eres persona natural o persona jurídica?",
        ayudaRapida: "Las personas jurídicas nacionales no pagan impuesto sobre dividendos recibidos de otras sociedades nacionales (Art. 48 ET). Las personas naturales sí tributan.",
        opciones: [
          { label: "Persona natural", nextNodeId: "residencia-div" },
          { label: "Persona jurídica nacional", nextNodeId: "resultado-pj-dividendos" },
        ],
      },
      {
        id: "resultado-pj-dividendos",
        tipo: "resultado",
        texto: "Dividendos entre sociedades nacionales: no gravados",
        recomendacion: "Los dividendos distribuidos entre sociedades nacionales son INCRNGO (Art. 48-49 ET), siempre que provengan de utilidades que ya pagaron impuesto corporativo. No se incluyen en la base gravable de la sociedad receptora.",
        enlaces: [{ label: "Ver Art. 49 ET", href: "/explorador?art=49" }],
      },
      {
        id: "residencia-div",
        tipo: "pregunta",
        texto: "¿Eres residente fiscal en Colombia?",
        ayudaRapida: "Los residentes tributan por cédula de dividendos con tarifas progresivas. Los no residentes tienen retención fija.",
        opciones: [
          { label: "Sí, soy residente", nextNodeId: "tipo-dividendo" },
          { label: "No, soy no residente", nextNodeId: "resultado-no-residente-div" },
        ],
      },
      {
        id: "tipo-dividendo",
        tipo: "pregunta",
        texto: "¿Los dividendos fueron distribuidos como gravados o no gravados (Art. 49 ET)?",
        ayudaRapida: "La sociedad que distribuye debe certificar si los dividendos son gravados (utilidades que no pagaron impuesto corporativo) o no gravados (ya pagaron el 35%). Revisa el certificado.",
        opciones: [
          { label: "No gravados (ya pagaron impuesto corporativo)", nextNodeId: "resultado-sub1" },
          { label: "Gravados (no pagaron impuesto corporativo)", nextNodeId: "resultado-sub2" },
          { label: "No estoy seguro", nextNodeId: "resultado-sub1" },
        ],
      },
      {
        id: "resultado-sub1",
        tipo: "resultado",
        texto: "Sub-cédula 1: Dividendos no gravados",
        recomendacion: "Los primeros 1.090 UVT ($57.087.660 en 2026) están exentos. El exceso tributa con tarifa progresiva del 0% al 20% según el Art. 242 ET. Este es el caso más común cuando la sociedad pagó impuesto corporativo sobre sus utilidades.",
        enlaces: [
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
          { label: "Ver Art. 242 ET", href: "/explorador?art=242" },
        ],
      },
      {
        id: "resultado-sub2",
        tipo: "resultado",
        texto: "Sub-cédula 2: Dividendos gravados",
        recomendacion: "Se aplica primero la tarifa del Art. 240 (35%) sobre el dividendo gravado, y luego sobre el remanente se aplica la tabla del Art. 242. La carga total puede ser cercana al 48%. Verifique con la sociedad la certificación de dividendos.",
        enlaces: [
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
          { label: "Ver Art. 242 ET", href: "/explorador?art=242" },
        ],
      },
      {
        id: "resultado-no-residente-div",
        tipo: "resultado",
        texto: "Dividendos para no residentes",
        recomendacion: "No gravados: retención del 20%. Gravados: retención del 35% + 20% sobre el remanente. Verifique si existe CDI (Convenio de Doble Imposición) con su país que reduzca la tarifa de retención.",
        enlaces: [{ label: "Ver Art. 245 ET", href: "/explorador?art=245" }],
      },
    ],
  },
  {
    id: "ganancias-ocasionales-guia",
    titulo: "¿Tengo ganancias ocasionales?",
    descripcion: "Identifica si tus ingresos extraordinarios califican como ganancia ocasional y cómo tributan.",
    categoria: "renta",
    complejidad: "intermedia",
    nodoInicial: "tipo-ingreso-go",
    nodos: [
      {
        id: "tipo-ingreso-go",
        tipo: "pregunta",
        texto: "¿De qué tipo es el ingreso extraordinario que recibiste?",
        ayudaRapida: "Las ganancias ocasionales provienen de hechos no habituales: venta de bienes, herencias, loterías o donaciones.",
        opciones: [
          { label: "Venta de un bien (casa, carro, lote)", nextNodeId: "tiempo-posesion" },
          { label: "Herencia o legado", nextNodeId: "resultado-herencia" },
          { label: "Lotería, rifa o apuesta", nextNodeId: "resultado-loteria" },
          { label: "Donación recibida", nextNodeId: "resultado-donacion" },
        ],
      },
      {
        id: "tiempo-posesion",
        tipo: "pregunta",
        texto: "¿Poseíste el bien por más de 2 años?",
        ayudaRapida: "Solo es ganancia ocasional si lo tuviste más de 2 años. Si fue menos, se trata como renta ordinaria.",
        opciones: [
          { label: "Sí, más de 2 años", nextNodeId: "vivienda-go" },
          { label: "No, menos de 2 años", nextNodeId: "resultado-renta-ordinaria" },
        ],
      },
      {
        id: "vivienda-go",
        tipo: "pregunta",
        texto: "¿El bien vendido es tu casa o apartamento de habitación?",
        ayudaRapida: "La venta de vivienda habitual tiene una exención especial de las primeras 7.500 UVT ($392.805.000) de la ganancia.",
        opciones: [
          { label: "Sí, es mi vivienda habitual", nextNodeId: "resultado-vivienda" },
          { label: "No, es otro tipo de bien", nextNodeId: "resultado-go-general" },
        ],
      },
      {
        id: "resultado-vivienda",
        tipo: "resultado",
        texto: "Ganancia ocasional con exención por vivienda",
        recomendacion: "La ganancia (precio de venta - costo fiscal) tributa al 15%, pero las primeras 7.500 UVT ($392.805.000 en 2026) están exentas si el dinero se destina a otra vivienda dentro de 1 año o se deposita en cuenta AFC.",
        enlaces: [
          { label: "Ver Art. 311-1 ET", href: "/explorador?art=311-1" },
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
        ],
      },
      {
        id: "resultado-go-general",
        tipo: "resultado",
        texto: "Ganancia ocasional gravada al 15%",
        recomendacion: "La ganancia se calcula como precio de venta menos costo fiscal del bien. Se grava a tarifa fija del 15%. Recuerde actualizar el costo fiscal con los reajustes fiscales anuales para reducir la ganancia gravable.",
        enlaces: [{ label: "Ver Art. 300-313 ET", href: "/explorador?art=300" }],
      },
      {
        id: "resultado-renta-ordinaria",
        tipo: "resultado",
        texto: "No es ganancia ocasional, es renta ordinaria",
        recomendacion: "Si poseíste el bien menos de 2 años, la utilidad en la venta se trata como renta ordinaria y se suma a tu cédula general, tributando con la tabla progresiva del Art. 241 (hasta 39%).",
        enlaces: [{ label: "Ver Art. 300 ET", href: "/explorador?art=300" }],
      },
      {
        id: "resultado-herencia",
        tipo: "resultado",
        texto: "Herencias: ganancia ocasional con exención",
        recomendacion: "Las herencias y legados son ganancia ocasional. Las primeras 3.250 UVT ($170.215.500) están exentas. El exceso tributa al 15%. Asignaciones por porción conyugal también tienen exención de 3.250 UVT.",
        enlaces: [{ label: "Ver Art. 307 ET", href: "/explorador?art=307" }],
      },
      {
        id: "resultado-loteria",
        tipo: "resultado",
        texto: "Loterías y rifas: tarifa del 20%",
        recomendacion: "Las ganancias por loterías, rifas, apuestas y similares tributan al 20% (no 15%). La retención se practica en el momento del pago por parte del operador del juego. Primeras 48 UVT exentas.",
        enlaces: [{ label: "Ver Art. 304-306 ET", href: "/explorador?art=304" }],
      },
      {
        id: "resultado-donacion",
        tipo: "resultado",
        texto: "Donaciones recibidas: ganancia ocasional",
        recomendacion: "Las donaciones recibidas son ganancia ocasional para el donatario. Las primeras 1.625 UVT están exentas ($85.107.750 en 2026). El exceso tributa al 15%. El donante puede tomar descuento tributario del 25% de la donación.",
        enlaces: [{ label: "Ver Art. 302 ET", href: "/explorador?art=302" }],
      },
    ],
  },
  {
    id: "anticipo-renta",
    titulo: "¿Cómo funciona el anticipo de renta?",
    descripcion: "Entiende cómo se calcula el anticipo del impuesto de renta para el año siguiente.",
    categoria: "renta",
    complejidad: "basica",
    nodoInicial: "anos-declarando",
    nodos: [
      {
        id: "anos-declarando",
        tipo: "pregunta",
        texto: "¿Cuántas veces has declarado renta?",
        ayudaRapida: "El porcentaje del anticipo varía según si es tu primera, segunda o tercera declaración en adelante.",
        opciones: [
          { label: "Es mi primera declaración", nextNodeId: "resultado-primera" },
          { label: "Es mi segunda declaración", nextNodeId: "resultado-segunda" },
          { label: "Tres o más declaraciones", nextNodeId: "resultado-tercera" },
        ],
      },
      {
        id: "resultado-primera",
        tipo: "resultado",
        texto: "Anticipo del 25%",
        recomendacion: "Para la primera declaración, el anticipo es el 25% del impuesto neto de renta del periodo. Se resta de las retenciones del año siguiente. Fórmula: (Impuesto neto × 25%) − Retenciones del año.",
        enlaces: [
          { label: "Ver Art. 807 ET", href: "/explorador?art=807" },
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
        ],
      },
      {
        id: "resultado-segunda",
        tipo: "resultado",
        texto: "Anticipo del 50%",
        recomendacion: "Para la segunda declaración, el anticipo sube al 50%. Se calcula como el promedio entre dos métodos: (1) impuesto neto del año actual × 50% y (2) impuesto neto del año anterior × 50%. Se toma el mayor.",
        enlaces: [
          { label: "Ver Art. 807-809 ET", href: "/explorador?art=807" },
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
        ],
      },
      {
        id: "resultado-tercera",
        tipo: "resultado",
        texto: "Anticipo del 75%",
        recomendacion: "A partir de la tercera declaración, el anticipo es el 75%. Se calcula igual que en la segunda: promedio de los dos métodos, se toma el mayor, y se restan las retenciones del año. Si el resultado es negativo, el anticipo es cero.",
        enlaces: [
          { label: "Ver Art. 807-809 ET", href: "/explorador?art=807" },
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
        ],
      },
    ],
  },
  {
    id: "obligaciones-nuevo-contribuyente",
    titulo: "Soy nuevo contribuyente, ¿qué debo hacer?",
    descripcion: "Guía paso a paso para quienes inician actividades económicas y deben cumplir obligaciones tributarias.",
    categoria: "general",
    complejidad: "basica",
    nodoInicial: "tipo-persona-nuevo",
    nodos: [
      {
        id: "tipo-persona-nuevo",
        tipo: "pregunta",
        texto: "¿Vas a operar como persona natural o vas a crear una empresa (persona jurídica)?",
        ayudaRapida: "La persona natural opera con su cédula y RUT personal. La persona jurídica (SAS, Ltda) se registra como entidad separada en Cámara de Comercio.",
        opciones: [
          { label: "Persona natural", nextNodeId: "actividad-nuevo-pn" },
          { label: "Persona jurídica (empresa)", nextNodeId: "resultado-nuevo-pj" },
        ],
      },
      {
        id: "actividad-nuevo-pn",
        tipo: "pregunta",
        texto: "¿Tu actividad genera ingresos superiores a 3.500 UVT al año ($183.309.000)?",
        ayudaRapida: "Este tope define si eres responsable de IVA y si debes facturar electrónicamente.",
        opciones: [
          { label: "Sí, espero superar ese monto", nextNodeId: "resultado-pn-responsable" },
          { label: "No, serán menores", nextNodeId: "resultado-pn-no-responsable" },
        ],
      },
      {
        id: "resultado-nuevo-pj",
        tipo: "resultado",
        texto: "Obligaciones de persona jurídica nueva",
        recomendacion: "1. Registrarte en Cámara de Comercio. 2. Obtener RUT con responsabilidades (renta, IVA, retención, ICA). 3. Habilitar facturación electrónica ante DIAN. 4. Implementar nómina electrónica si tienes empleados. 5. Declarar renta anual (F110), IVA bimestral/cuatrimestral, retenciones mensuales. 6. Pagar seguridad social y parafiscales.",
        enlaces: [
          { label: "Declaración Renta PJ", href: "/declaracion-renta-juridicas" },
          { label: "Calendario Tributario", href: "/calendario" },
        ],
      },
      {
        id: "resultado-pn-responsable",
        tipo: "resultado",
        texto: "Persona natural responsable de IVA",
        recomendacion: "1. Actualizar RUT con responsabilidad de IVA. 2. Habilitar facturación electrónica. 3. Declarar IVA bimestral o cuatrimestral. 4. Declarar renta anual (F210). 5. Practicar retenciones si haces pagos. 6. Pagar seguridad social como independiente (40% del ingreso).",
        enlaces: [
          { label: "Declaración de Renta PN", href: "/declaracion-renta" },
          { label: "Calendario Tributario", href: "/calendario" },
        ],
      },
      {
        id: "resultado-pn-no-responsable",
        tipo: "resultado",
        texto: "Persona natural no responsable de IVA",
        recomendacion: "1. Inscribirte en el RUT (puedes hacerlo en línea). 2. No necesitas factura electrónica (pero puedes voluntariamente). 3. Verificar anualmente si superas topes para declarar renta. 4. Pagar seguridad social como independiente si generas ingresos >= 1 SMLMV.",
        enlaces: [
          { label: "Guía: ¿Debo declarar renta?", href: "/guias" },
          { label: "Calendario Tributario", href: "/calendario" },
        ],
      },
    ],
  },
  {
    id: "beneficios-zona-franca",
    titulo: "¿Me conviene la zona franca?",
    descripcion: "Evalúa si tu empresa puede beneficiarse del régimen de zona franca y sus incentivos tributarios.",
    categoria: "renta",
    complejidad: "avanzada",
    nodoInicial: "tipo-zf",
    nodos: [
      {
        id: "tipo-zf",
        tipo: "pregunta",
        texto: "¿Qué tipo de zona franca te interesa?",
        ayudaRapida: "Permanente: parques industriales con múltiples empresas. Especial (uniempresarial): un solo proyecto de alto impacto. Offshore: servicios especiales.",
        opciones: [
          { label: "Zona franca permanente (multiempresarial)", nextNodeId: "inversion-zf" },
          { label: "Zona franca especial (uniempresarial)", nextNodeId: "inversion-zfe" },
          { label: "No estoy seguro", nextNodeId: "inversion-zf" },
        ],
      },
      {
        id: "inversion-zf",
        tipo: "pregunta",
        texto: "¿Tu inversión y empleo cumplen los requisitos del plan maestro de la zona franca?",
        ayudaRapida: "Cada ZF tiene requisitos mínimos de inversión y generación de empleo según su plan maestro aprobado por MinCIT.",
        opciones: [
          { label: "Sí, cumplimos los requisitos", nextNodeId: "exportacion-zf" },
          { label: "No estoy seguro / estamos evaluando", nextNodeId: "resultado-evaluar-zf" },
        ],
      },
      {
        id: "inversion-zfe",
        tipo: "pregunta",
        texto: "¿Tu proyecto supera 150.000 SMLMV de inversión y genera al menos 150 empleos directos?",
        ayudaRapida: "Las zonas francas especiales (uniempresariales) requieren una inversión mínima alta y generación significativa de empleo.",
        opciones: [
          { label: "Sí", nextNodeId: "exportacion-zf" },
          { label: "No", nextNodeId: "resultado-no-califica-zfe" },
        ],
      },
      {
        id: "exportacion-zf",
        tipo: "pregunta",
        texto: "¿Más del 50% de tus ingresos provendrán de exportaciones?",
        ayudaRapida: "La reforma tributaria de 2022 condicionó la tarifa del 20% a que las ZF cumplan un porcentaje de exportación creciente.",
        opciones: [
          { label: "Sí, exportamos más del 50%", nextNodeId: "resultado-zf-20" },
          { label: "No, vendemos principalmente en Colombia", nextNodeId: "resultado-zf-35" },
        ],
      },
      {
        id: "resultado-zf-20",
        tipo: "resultado",
        texto: "Zona franca con tarifa del 20%",
        recomendacion: "Cumpliendo los requisitos de exportación, tu tarifa de renta es del 20% (vs. 35% del régimen ordinario). Adicionalmente: IVA 0% en materias primas importadas, no retención en pagos desde territorio aduanero nacional, y aplica la TTD mínima del 15%.",
        enlaces: [
          { label: "Ver Art. 240-1 ET", href: "/explorador?art=240-1" },
          { label: "Declaración Renta PJ", href: "/declaracion-renta-juridicas" },
        ],
      },
      {
        id: "resultado-zf-35",
        tipo: "resultado",
        texto: "Zona franca sin beneficio de tarifa",
        recomendacion: "Si no cumples el porcentaje de exportación, la tarifa será del 35% (régimen general). Sin embargo, conservas otros beneficios aduaneros y de IVA. Evalúa si las ventajas logísticas y aduaneras justifican la operación en zona franca.",
        enlaces: [{ label: "Ver Art. 240-1 ET", href: "/explorador?art=240-1" }],
      },
      {
        id: "resultado-evaluar-zf",
        tipo: "resultado",
        texto: "Evalúa los requisitos con el operador de la ZF",
        recomendacion: "Contacta al operador de la zona franca para conocer los requisitos específicos del plan maestro (inversión mínima, empleos, actividad permitida). El ahorro potencial es del 15% en tarifa de renta (20% vs 35%).",
      },
      {
        id: "resultado-no-califica-zfe",
        tipo: "resultado",
        texto: "No calificas para zona franca especial",
        recomendacion: "Considera una zona franca permanente (multiempresarial) donde los requisitos de inversión y empleo son menores. Alternativamente, evalúa incentivos ZOMAC o mega-inversiones.",
        enlaces: [{ label: "Declaración Renta PJ", href: "/declaracion-renta-juridicas" }],
      },
    ],
  },
  {
    id: "retencion-independientes",
    titulo: "Retención para trabajadores independientes",
    descripcion: "Determina qué retención en la fuente aplica sobre tus ingresos como trabajador independiente.",
    categoria: "retencion",
    complejidad: "intermedia",
    nodoInicial: "tipo-contrato-ind",
    nodos: [
      {
        id: "tipo-contrato-ind",
        tipo: "pregunta",
        texto: "¿Prestas servicios personales (consultoría, asesoría) o vendes bienes/productos?",
        ayudaRapida: "Los servicios personales tienen un régimen de retención diferente al de venta de bienes. La tarifa depende del concepto.",
        opciones: [
          { label: "Servicios personales", nextNodeId: "ingresos-3300" },
          { label: "Venta de bienes", nextNodeId: "resultado-retencion-compras" },
        ],
      },
      {
        id: "ingresos-3300",
        tipo: "pregunta",
        texto: "¿Tus ingresos del año anterior superaron 3.300 UVT ($172.834.200 en UVT 2026)?",
        ayudaRapida: "Si superaste este tope, te aplica la depuración y tabla del Art. 383 (igual que asalariados). Si no, aplica retención ordinaria por servicios.",
        opciones: [
          { label: "Sí, los superaron", nextNodeId: "resultado-tabla-383" },
          { label: "No, fueron menores", nextNodeId: "declarante-renta-ind" },
        ],
      },
      {
        id: "declarante-renta-ind",
        tipo: "pregunta",
        texto: "¿Eres declarante de renta?",
        ayudaRapida: "La tarifa de retención por servicios varía según seas declarante (4%) o no declarante (6%).",
        opciones: [
          { label: "Sí, declaro renta", nextNodeId: "resultado-retencion-4" },
          { label: "No declaro renta", nextNodeId: "resultado-retencion-6" },
        ],
      },
      {
        id: "resultado-tabla-383",
        tipo: "resultado",
        texto: "Retención por tabla del Art. 383 ET",
        recomendacion: "Al superar 3.300 UVT, tu pagador debe aplicar la tabla del Art. 383 (la misma de asalariados) depurando tu ingreso con aportes obligatorios, renta exenta del 25% y deducciones. Puedes entregar tu información al pagador para optimizar la retención.",
        enlaces: [
          { label: "Tablas de Retención", href: "/tablas/retencion" },
          { label: "Ver Art. 383 ET", href: "/explorador?art=383" },
        ],
      },
      {
        id: "resultado-retencion-4",
        tipo: "resultado",
        texto: "Retención del 4% por servicios (declarante)",
        recomendacion: "Como declarante de renta que presta servicios con ingresos menores a 3.300 UVT, te aplica retención del 4% sobre pagos que superen 4 UVT ($209.496). Si prestas servicios de honorarios (consultoría), puede ser 10%.",
        enlaces: [
          { label: "Tablas de Retención", href: "/tablas/retencion" },
          { label: "Ver Art. 392 ET", href: "/explorador?art=392" },
        ],
      },
      {
        id: "resultado-retencion-6",
        tipo: "resultado",
        texto: "Retención del 6% por servicios (no declarante)",
        recomendacion: "Como no declarante de renta que presta servicios, te aplica retención del 6% (o 11% si es por honorarios). Esta retención es tu impuesto final ya que no presentas declaración.",
        enlaces: [{ label: "Tablas de Retención", href: "/tablas/retencion" }],
      },
      {
        id: "resultado-retencion-compras",
        tipo: "resultado",
        texto: "Retención por compras",
        recomendacion: "La venta de bienes tiene retención del 2.5% (declarante) o 3.5% (no declarante) sobre pagos superiores a 27 UVT ($1.414.098). Para productos agrícolas sin procesamiento la tarifa es del 1.5%.",
        enlaces: [{ label: "Tablas de Retención", href: "/tablas/retencion" }],
      },
    ],
  },
  {
    id: "nomina-electronica",
    titulo: "¿Debo implementar nómina electrónica?",
    descripcion: "Determina si estás obligado a transmitir el documento soporte de pago de nómina electrónica a la DIAN.",
    categoria: "laboral",
    complejidad: "basica",
    nodoInicial: "tiene-empleados",
    nodos: [
      {
        id: "tiene-empleados",
        tipo: "pregunta",
        texto: "¿Tienes trabajadores vinculados por contrato laboral?",
        ayudaRapida: "La nómina electrónica solo aplica si tienes empleados con contrato laboral. Los contratistas de prestación de servicios no cuentan.",
        opciones: [
          { label: "Sí, tengo empleados", nextNodeId: "declara-renta-ne" },
          { label: "No tengo empleados", nextNodeId: "resultado-no-aplica-ne" },
        ],
      },
      {
        id: "declara-renta-ne",
        tipo: "pregunta",
        texto: "¿Estás obligado a declarar renta y quieres deducir los costos de nómina?",
        ayudaRapida: "Desde 2022, la nómina electrónica es requisito para soportar costos y deducciones por pagos laborales en la declaración de renta.",
        opciones: [
          { label: "Sí, declaro renta", nextNodeId: "resultado-obligado-ne" },
          { label: "No declaro renta", nextNodeId: "resultado-recomendado-ne" },
        ],
      },
      {
        id: "resultado-obligado-ne",
        tipo: "resultado",
        texto: "Sí, debes implementar nómina electrónica",
        recomendacion: "Debes transmitir el documento soporte de pago de nómina electrónica a la DIAN dentro de los 10 primeros días del mes siguiente al pago. Sin este documento no podrás deducir tus costos laborales en la declaración de renta.",
        enlaces: [{ label: "Ver Art. 616-1 ET", href: "/explorador?art=616-1" }],
      },
      {
        id: "resultado-recomendado-ne",
        tipo: "resultado",
        texto: "Recomendado pero no estrictamente obligatorio",
        recomendacion: "Aunque no declares renta actualmente, es recomendable implementar la nómina electrónica para tener soportes válidos. Si en el futuro superas los topes, necesitarás estos documentos para deducir costos laborales.",
      },
      {
        id: "resultado-no-aplica-ne",
        tipo: "resultado",
        texto: "No necesitas nómina electrónica",
        recomendacion: "Sin empleados con contrato laboral, no tienes obligación de nómina electrónica. Si contratas por prestación de servicios, el soporte es la factura electrónica o el documento soporte de no obligados a facturar.",
      },
    ],
  },
  {
    id: "ica-industria-comercio",
    titulo: "¿Debo pagar ICA?",
    descripcion: "Determina si estás sujeto al Impuesto de Industria y Comercio en tu municipio.",
    categoria: "general",
    complejidad: "intermedia",
    nodoInicial: "actividad-ica",
    nodos: [
      {
        id: "actividad-ica",
        tipo: "pregunta",
        texto: "¿Realizas actividades industriales, comerciales o de servicios en algún municipio de Colombia?",
        ayudaRapida: "El ICA grava toda actividad económica con ánimo de lucro realizada en un municipio. Es diferente al impuesto de renta (que es nacional).",
        opciones: [
          { label: "Sí, tengo actividad económica", nextNodeId: "tipo-actividad-ica" },
          { label: "No, soy asalariado exclusivamente", nextNodeId: "resultado-no-ica" },
        ],
      },
      {
        id: "tipo-actividad-ica",
        tipo: "pregunta",
        texto: "¿En qué tipo de actividad se clasifica tu negocio?",
        ayudaRapida: "Las tarifas de ICA varían según la actividad: industrial (2-7 por mil), comercial (4-11.04 por mil), servicios (2-10 por mil). Cada municipio fija sus tarifas.",
        opciones: [
          { label: "Industrial (producción, manufactura)", nextNodeId: "regimen-ica" },
          { label: "Comercial (compra y venta de bienes)", nextNodeId: "regimen-ica" },
          { label: "Servicios (consultoría, profesiones, tecnología)", nextNodeId: "regimen-ica" },
        ],
      },
      {
        id: "regimen-ica",
        tipo: "pregunta",
        texto: "¿Estás inscrito en el Régimen SIMPLE?",
        ayudaRapida: "El SIMPLE incluye el ICA en la tarifa unificada. Si estás en SIMPLE, no declaras ICA por separado.",
        opciones: [
          { label: "Sí, estoy en el SIMPLE", nextNodeId: "resultado-simple-ica" },
          { label: "No, estoy en régimen ordinario", nextNodeId: "resultado-ica-obligado" },
        ],
      },
      {
        id: "resultado-ica-obligado",
        tipo: "resultado",
        texto: "Sí, debes pagar ICA",
        recomendacion: "Debes inscribirte en la Secretaría de Hacienda de tu municipio, declarar y pagar ICA periódicamente (bimestral o anual según el municipio). La base gravable son tus ingresos ordinarios y extraordinarios. Recuerda que el ICA pagado es descuento tributario del 50% en renta.",
        enlaces: [{ label: "Ver Art. 115 ET (descuento)", href: "/explorador?art=115" }],
      },
      {
        id: "resultado-simple-ica",
        tipo: "resultado",
        texto: "ICA incluido en el SIMPLE",
        recomendacion: "En el Régimen SIMPLE, el ICA está integrado en la tarifa unificada. No necesitas declarar ICA por separado ante el municipio. La declaración del SIMPLE reemplaza la del ICA.",
      },
      {
        id: "resultado-no-ica",
        tipo: "resultado",
        texto: "No estás sujeto a ICA",
        recomendacion: "Los asalariados exclusivos no realizan actividades gravadas con ICA. Este impuesto solo aplica para quienes realizan actividades económicas por cuenta propia (industriales, comerciales o de servicios).",
      },
    ],
  },
  {
    id: "devolucion-saldo-favor",
    titulo: "¿Cómo solicito devolución de saldo a favor?",
    descripcion: "Conoce el procedimiento para solicitar la devolución o compensación de saldos a favor ante la DIAN.",
    categoria: "general",
    complejidad: "intermedia",
    nodoInicial: "tipo-impuesto-dev",
    nodos: [
      {
        id: "tipo-impuesto-dev",
        tipo: "pregunta",
        texto: "¿De qué impuesto proviene tu saldo a favor?",
        ayudaRapida: "El procedimiento varía según el impuesto. Los más comunes son renta e IVA. El saldo a favor aparece en la última casilla de tu declaración.",
        opciones: [
          { label: "Impuesto de renta", nextNodeId: "facturacion-dev" },
          { label: "IVA", nextNodeId: "exportador-dev" },
        ],
      },
      {
        id: "facturacion-dev",
        tipo: "pregunta",
        texto: "¿Emites factura electrónica y estás al día con tus obligaciones tributarias?",
        ayudaRapida: "La DIAN verifica que estés al día antes de aprobar la devolución. Si tienes factura electrónica, puedes acceder a devolución automática (más rápida).",
        opciones: [
          { label: "Sí, tengo factura electrónica al día", nextNodeId: "resultado-dev-automatica" },
          { label: "No tengo factura electrónica", nextNodeId: "resultado-dev-manual" },
        ],
      },
      {
        id: "exportador-dev",
        tipo: "pregunta",
        texto: "¿Eres exportador o productor de bienes exentos?",
        ayudaRapida: "Los exportadores y productores de bienes exentos tienen derecho a devolución permanente del IVA descontable pagado en sus compras.",
        opciones: [
          { label: "Sí, soy exportador/productor de exentos", nextNodeId: "resultado-dev-iva-exportador" },
          { label: "No", nextNodeId: "resultado-dev-iva-general" },
        ],
      },
      {
        id: "resultado-dev-automatica",
        tipo: "resultado",
        texto: "Devolución automática (30 días)",
        recomendacion: "Con factura electrónica puedes solicitar devolución automática. La DIAN tiene 15 días hábiles para resolver (30 con verificación). Solicita por MUISCA → Trámites → Devoluciones. No necesitas garantía bancaria para montos menores a 1.000 UVT.",
        enlaces: [
          { label: "Ver Art. 855 ET", href: "/explorador?art=855" },
          { label: "Calendario Tributario", href: "/calendario" },
        ],
      },
      {
        id: "resultado-dev-manual",
        tipo: "resultado",
        texto: "Devolución ordinaria (50 días)",
        recomendacion: "Sin factura electrónica, la devolución es ordinaria: 50 días hábiles. Debes presentar solicitud por MUISCA con certificación de contador y garantía bancaria (por 2 años al 100% del saldo). Alternativa: compensar contra otros impuestos.",
        enlaces: [{ label: "Ver Art. 850-865 ET", href: "/explorador?art=850" }],
      },
      {
        id: "resultado-dev-iva-exportador",
        tipo: "resultado",
        texto: "Devolución de IVA para exportadores",
        recomendacion: "Como exportador tienes derecho permanente a devolución del IVA de tus compras. Presenta solicitud bimestral ante la DIAN. La tarifa de IVA en exportaciones es 0% (exenta), así que siempre tendrás saldo a favor.",
        enlaces: [{ label: "Ver Art. 481 ET", href: "/explorador?art=481" }],
      },
      {
        id: "resultado-dev-iva-general",
        tipo: "resultado",
        texto: "Saldo a favor en IVA: compensar o devolver",
        recomendacion: "Si tu IVA descontable supera tu IVA generado, tienes saldo a favor. Puedes: (1) imputarlo al siguiente periodo, (2) solicitar compensación contra otros impuestos nacionales, o (3) pedir devolución con los mismos requisitos que en renta.",
        enlaces: [{ label: "Ver Art. 815 ET", href: "/explorador?art=815" }],
      },
    ],
  },
  {
    id: "regimen-tributario-especial",
    titulo: "¿Mi entidad califica como ESAL?",
    descripcion: "Determina si tu entidad sin ánimo de lucro puede pertenecer al Régimen Tributario Especial y sus beneficios.",
    categoria: "renta",
    complejidad: "avanzada",
    nodoInicial: "tipo-entidad-rte",
    nodos: [
      {
        id: "tipo-entidad-rte",
        tipo: "pregunta",
        texto: "¿Qué tipo de entidad es?",
        ayudaRapida: "El RTE aplica a fundaciones, asociaciones, corporaciones y cooperativas sin ánimo de lucro constituidas bajo la ley colombiana.",
        opciones: [
          { label: "Fundación", nextNodeId: "actividad-meritoria" },
          { label: "Asociación o corporación", nextNodeId: "actividad-meritoria" },
          { label: "Cooperativa", nextNodeId: "resultado-cooperativa" },
          { label: "Otro tipo de entidad", nextNodeId: "resultado-no-califica-rte" },
        ],
      },
      {
        id: "actividad-meritoria",
        tipo: "pregunta",
        texto: "¿La entidad realiza actividades meritorias (educación, salud, cultura, ciencia, deporte, medio ambiente, desarrollo social)?",
        ayudaRapida: "El Art. 359 ET lista 13 actividades meritorias. La entidad debe tener como objeto principal alguna de estas actividades.",
        opciones: [
          { label: "Sí, nuestra actividad es meritoria", nextNodeId: "reinversion-rte" },
          { label: "No estoy seguro", nextNodeId: "reinversion-rte" },
          { label: "No, nuestra actividad no es meritoria", nextNodeId: "resultado-no-califica-rte" },
        ],
      },
      {
        id: "reinversion-rte",
        tipo: "pregunta",
        texto: "¿La entidad reinvierte el 100% de sus excedentes en su objeto social?",
        ayudaRapida: "Para mantener el beneficio del RTE, todos los excedentes deben reinvertirse en la actividad meritoria. Si se distribuyen, se pierde el beneficio.",
        opciones: [
          { label: "Sí, reinvertimos todo", nextNodeId: "resultado-rte-exento" },
          { label: "No, distribuimos parte de los excedentes", nextNodeId: "resultado-rte-20" },
        ],
      },
      {
        id: "resultado-rte-exento",
        tipo: "resultado",
        texto: "Régimen Tributario Especial: excedente exento",
        recomendacion: "Si reinviertes el 100% del excedente en tu objeto social, la tarifa efectiva es 0%. Debes registrarte en el RTE ante la DIAN (proceso de calificación anual) y cumplir con transparencia: publicar estados financieros y memoria económica.",
        enlaces: [
          { label: "Ver Art. 356-364 ET", href: "/explorador?art=356" },
          { label: "Declaración Renta PJ", href: "/declaracion-renta-juridicas" },
        ],
      },
      {
        id: "resultado-rte-20",
        tipo: "resultado",
        texto: "Régimen Tributario Especial: tarifa del 20%",
        recomendacion: "Si no reinviertes la totalidad de los excedentes, la parte no reinvertida tributa al 20%. Adicionalmente, podrías perder la calificación en el RTE si los excedentes se distribuyen entre los miembros.",
        enlaces: [{ label: "Ver Art. 356 ET", href: "/explorador?art=356" }],
      },
      {
        id: "resultado-cooperativa",
        tipo: "resultado",
        texto: "Cooperativas: régimen especial",
        recomendacion: "Las cooperativas pertenecen al RTE con tarifa del 20% sobre el beneficio neto. Deben destinar el 20% del excedente a educación formal (ICETEX/SENA). Los excedentes que se destinen a fondos de educación y solidaridad son exentos.",
        enlaces: [{ label: "Ver Art. 19 ET", href: "/explorador?art=19" }],
      },
      {
        id: "resultado-no-califica-rte",
        tipo: "resultado",
        texto: "No califica para el Régimen Tributario Especial",
        recomendacion: "Tu entidad tributa bajo el régimen ordinario (tarifa del 35%). Para calificar al RTE, debe ser ESAL con actividad meritoria, constituida bajo ley colombiana, y solicitar calificación ante la DIAN antes del 31 de marzo.",
      },
    ],
  },
  {
    id: "precios-transferencia",
    titulo: "¿Estoy obligado a precios de transferencia?",
    descripcion: "Determina si tu empresa debe cumplir con el régimen de precios de transferencia por operaciones con vinculados del exterior.",
    categoria: "renta",
    complejidad: "avanzada",
    nodoInicial: "vinculados-ext",
    nodos: [
      {
        id: "vinculados-ext",
        tipo: "pregunta",
        texto: "¿Tu empresa realizó operaciones con vinculados económicos del exterior o en zonas francas?",
        ayudaRapida: "Vinculados: casa matriz, subsidiarias, filiales, sucursales del exterior, o personas con participación > 50%. También aplica para operaciones con zonas francas.",
        opciones: [
          { label: "Sí, tenemos operaciones con vinculados", nextNodeId: "topes-pt" },
          { label: "No tenemos vinculados del exterior", nextNodeId: "jurisdiccion-pt" },
        ],
      },
      {
        id: "jurisdiccion-pt",
        tipo: "pregunta",
        texto: "¿Realizaste operaciones con personas en jurisdicciones no cooperantes (paraísos fiscales)?",
        ayudaRapida: "Las operaciones con paraísos fiscales se tratan como si fueran con vinculados, aunque no haya relación societaria.",
        opciones: [
          { label: "Sí", nextNodeId: "topes-pt" },
          { label: "No", nextNodeId: "resultado-no-pt" },
        ],
      },
      {
        id: "topes-pt",
        tipo: "pregunta",
        texto: "¿Tu patrimonio bruto supera 100.000 UVT ($5.237.400.000) o tus ingresos brutos superan 61.000 UVT ($3.194.814.000)?",
        ayudaRapida: "Solo los contribuyentes que superen alguno de estos topes deben preparar documentación comprobatoria y declaración informativa.",
        opciones: [
          { label: "Sí, supero alguno de los topes", nextNodeId: "resultado-obligado-pt" },
          { label: "No, estoy por debajo de ambos topes", nextNodeId: "resultado-parcial-pt" },
        ],
      },
      {
        id: "resultado-obligado-pt",
        tipo: "resultado",
        texto: "Obligado a precios de transferencia completo",
        recomendacion: "Debes: (1) Preparar documentación comprobatoria (estudio de precios de transferencia), (2) Presentar declaración informativa (Formato 120) ante la DIAN, (3) Presentar informe local, maestro y país por país si aplica. Plazo: según calendario tributario. El principio rector es la plena competencia (arm's length).",
        enlaces: [
          { label: "Ver Art. 260-1 a 260-11 ET", href: "/explorador?art=260-1" },
          { label: "Calendario Tributario", href: "/calendario" },
        ],
      },
      {
        id: "resultado-parcial-pt",
        tipo: "resultado",
        texto: "Obligación parcial de precios de transferencia",
        recomendacion: "Aunque no superes los topes para documentación comprobatoria, debes aplicar el principio de plena competencia en tus operaciones con vinculados. La DIAN puede requerir información sobre estas operaciones en cualquier momento.",
        enlaces: [{ label: "Ver Art. 260-2 ET", href: "/explorador?art=260-2" }],
      },
      {
        id: "resultado-no-pt",
        tipo: "resultado",
        texto: "No estás obligado a precios de transferencia",
        recomendacion: "Sin operaciones con vinculados del exterior ni con jurisdicciones no cooperantes, no tienes obligación de precios de transferencia. Si en el futuro realizas este tipo de operaciones, revisa los topes.",
      },
    ],
  },
  {
    id: "impuestos-saludables",
    titulo: "¿Me aplican los impuestos saludables?",
    descripcion: "Determina si tus productos están sujetos a los nuevos impuestos saludables creados por la Ley 2277 de 2022.",
    categoria: "general",
    complejidad: "basica",
    nodoInicial: "tipo-producto-sal",
    nodos: [
      {
        id: "tipo-producto-sal",
        tipo: "pregunta",
        texto: "¿Produces, importas o vendes alguno de estos productos?",
        ayudaRapida: "Los impuestos saludables gravan tres categorías: ultraprocesados, bebidas azucaradas y plásticos de un solo uso. Son impuestos nacionales administrados por la DIAN.",
        opciones: [
          { label: "Alimentos ultraprocesados", nextNodeId: "tipo-ultra" },
          { label: "Bebidas azucaradas", nextNodeId: "resultado-bebidas" },
          { label: "Envases plásticos de un solo uso", nextNodeId: "resultado-plastico" },
          { label: "Ninguno de los anteriores", nextNodeId: "resultado-no-aplica-sal" },
        ],
      },
      {
        id: "tipo-ultra",
        tipo: "pregunta",
        texto: "¿El producto tiene sellos de advertencia (exceso de sodio, azúcar o grasas saturadas)?",
        ayudaRapida: "El impuesto aplica a productos con sellos frontales de advertencia según la Resolución 810 de 2021 del MinSalud.",
        opciones: [
          { label: "Sí, tiene sellos de advertencia", nextNodeId: "resultado-ultraprocesados" },
          { label: "No tiene sellos", nextNodeId: "resultado-no-aplica-sal" },
        ],
      },
      {
        id: "resultado-ultraprocesados",
        tipo: "resultado",
        texto: "Sujeto al impuesto a ultraprocesados",
        recomendacion: "Los alimentos ultraprocesados con sellos de advertencia pagan un impuesto ad-valorem progresivo: 10% (2023), 15% (2024), 20% (2025 en adelante) sobre el precio de venta. Se declara bimestralmente.",
      },
      {
        id: "resultado-bebidas",
        tipo: "resultado",
        texto: "Sujeto al impuesto a bebidas azucaradas",
        recomendacion: "Las bebidas con azúcar añadida (gaseosas, jugos procesados, bebidas energizantes) pagan un impuesto específico por contenido de azúcar: $28/100ml (2023, indexado con IPC). Cerveza y vinos artesanales están excluidos.",
      },
      {
        id: "resultado-plastico",
        tipo: "resultado",
        texto: "Sujeto al impuesto al plástico",
        recomendacion: "Los envases y empaques plásticos de un solo uso usados para comercializar productos pagan $50 por gramo de envase. Se causa en la venta por el productor o en la importación. Envases retornables y reciclados certificados están excluidos.",
      },
      {
        id: "resultado-no-aplica-sal",
        tipo: "resultado",
        texto: "No te aplican los impuestos saludables",
        recomendacion: "Tus productos no están sujetos a estos impuestos. Si cambias tu línea de productos o comienzas a producir/importar bienes de las categorías gravadas, revisa tu obligación.",
      },
    ],
  },
];
